// The equipped weapon rides the controller grip pose.
//
// Each equipped item is its own render object (weapons: one class per
// category, ~140, created via the factory table at 0x9C2240 on item
// data[1]). The player entity holds them in a pointer array at +0xDF8
// indexed by the object's slot byte (+0x188): weapon = slot 6 =
// entity+0xE10 (mag slot 1, armor/shield slot 2). The shared base draw
// virtual (vtbl+0x08 = 0x5C4068: hide flag byte +0xF1, then 0x5C407C ->
// NJ model draw 0x83046C) is the on-the-floor representation and draws
// nothing for the held weapon. The held weapon draws through +0x60
// (0x5E8020) and +0x68 (0x5E88CC), which both funnel into 0x5E8088
// (thiscall, this = the weapon object). While that runs with this ==
// [entity+0xE10], every WORLD SetTransform belongs to the weapon.
//
// Re-seat: for each bracketed matrix, rel = part_world x inverse(root)
// (root = the bracket's first matrix, or the attach bone), and the
// substituted world = rel x grip_offset x WorldFromTracking(right hand
// pose). With no hand pose this frame nothing is substituted and the
// weapon follows the game's animation. Bracketed draws are exempt from
// head-trim suppression and body culling (ExemptingDraws()).
//
// Two-handed weapons: (1) the composite held-model draw 0x5E84A8 draws
// one half per call for twin swords and mechguns; halves alternate
// main/off, so odd composite brackets go to the left grip. (2) Funnel
// duals (daggers, knuckles) draw both halves in one bracket; the off-hand
// tail is found by its parts drifting against the root (same-hand parts
// hold within +-0.002 units) and goes to the left grip. Both only for
// two-handed kinds ([vr] twin_split).
//
// [vr] weapon_grip, weapon_scale (uniform scale about the grip, re-seated
// draws only).
#pragma once

#include <cmath>
#include <cstdint>

#include "MinHook.h"
#include "psobbvr_gamecam.hpp"
#include "psobbvr_log.hpp"
#include "psobbvr_probe.hpp"
#include "psobbvr_vr.hpp"

namespace weapongrip {

// The weapon's held-model draw: common callee of the draw-phase virtuals
// +0x60 (0x5E8020) and +0x68 (0x5E88CC), the same in every weapon vtable.
constexpr uintptr_t WEAPON_HELD_DRAW = 0x005E8088;
// Player entity + 0xE10 = the equipped weapon's render object (slot 6).
constexpr uintptr_t PLAYER_WEAPON_SLOT = 0xE10;
// Weapon object fields (base ctor 0x5E959C): byte +0xF3 = item category
// (data[1], < 0xED); dword +0x200 = its ItemPMT stats record. PMT byte
// +0x1F = projectile type (logged only; not the gun test).
constexpr uintptr_t WEAPON_CATEGORY_OFFSET = 0xF3;
constexpr uintptr_t WEAPON_PMT_OFFSET = 0x200;
constexpr uintptr_t PMT_PROJECTILE_OFFSET = 0x1F;
// The gun test: ItemPMT maps each item class (data[1]; every rare weapon
// is its own class) to one of 19 base kinds (table at root+0x14), and a
// weapon is a gun iff its kind is 06 handgun, 07 rifle, 08 mechgun, 09
// shot or 11 launcher. (Projectile type is not reliable: Izmaela, Windmill
// and Mercurius Rod have one but are swung.) The kinds also pick the
// two-handers for the twin split. Baked from this client's ItemPMT;
// tools\weaponsurvey.py --emit-cpp regenerates the table.
constexpr uint8_t WEAPON_KIND_KNUCKLE = 0x00;
constexpr uint8_t WEAPON_KIND_DAGGER = 0x03;
constexpr uint8_t WEAPON_KIND_HANDGUN = 0x06;
constexpr uint8_t WEAPON_KIND_RIFLE = 0x07;
constexpr uint8_t WEAPON_KIND_MECHGUN = 0x08;
constexpr uint8_t WEAPON_KIND_SHOT = 0x09;
constexpr uint8_t WEAPON_KIND_TWIN_SWORD = 0x0F;
constexpr uint8_t WEAPON_KIND_LAUNCHER = 0x11;
constexpr uint8_t WEAPON_KIND_NONE = 0xFF;  // unreadable / no weapon
// Generated by tools\weaponsurvey.py --emit-cpp from ItemPMT.prs (the kind
// table at root+0x14): item category (data[1]) -> base weapon kind, 0xED entries.
constexpr uint8_t WEAPON_KIND_TABLE[0xED] = {
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x00,  // 0x00
    0x10, 0x04, 0x07, 0x07, 0x09, 0x09, 0x10, 0x0B, 0x03, 0x03, 0x01, 0x07, 0x07, 0x0B, 0x06, 0x01,  // 0x10
    0x02, 0x02, 0x0B, 0x01, 0x0C, 0x0C, 0x06, 0x01, 0x10, 0x10, 0x01, 0x10, 0x01, 0x01, 0x0E, 0x0E,  // 0x20
    0x0E, 0x02, 0x02, 0x02, 0x02, 0x02, 0x03, 0x03, 0x03, 0x03, 0x04, 0x04, 0x04, 0x04, 0x04, 0x05,  // 0x30
    0x05, 0x05, 0x06, 0x06, 0x06, 0x07, 0x07, 0x08, 0x08, 0x08, 0x07, 0x08, 0x08, 0x09, 0x09, 0x0A,  // 0x40
    0x0A, 0x01, 0x0A, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0C, 0x0C, 0x0C, 0x0C, 0x0E, 0x0C,  // 0x50
    0x0D, 0x0D, 0x03, 0x04, 0x04, 0x07, 0x07, 0x09, 0x0B, 0x0D, 0x06, 0x07, 0x08, 0x09, 0x0C, 0x01,  // 0x60
    0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0E, 0x0D, 0x09, 0x07,  // 0x70
    0x04, 0x10, 0x0A, 0x08, 0x08, 0x0A, 0x10, 0x10, 0x05, 0x0F, 0x10, 0x11, 0x12, 0x11, 0x03, 0x02,  // 0x80
    0x01, 0x11, 0x12, 0x12, 0x0D, 0x0E, 0x12, 0x02, 0x0D, 0x07, 0x0E, 0x0D, 0x05, 0x02, 0x09, 0x0B,  // 0x90
    0x0F, 0x05, 0x0D, 0x06, 0x12, 0x0F, 0x11, 0x12, 0x00, 0x01, 0x05, 0x01, 0x01, 0x08, 0x02, 0x06,  // 0xA0
    0x08, 0x07, 0x01, 0x0E, 0x01, 0x00, 0x10, 0x10, 0x0F, 0x01, 0x04, 0x04, 0x03, 0x04, 0x04, 0x06,  // 0xB0
    0x11, 0x11, 0x0C, 0x0A, 0x0B, 0x0B, 0x10, 0x10, 0x03, 0x0A, 0x01, 0x04, 0x02, 0x07, 0x04, 0x04,  // 0xC0
    0x02, 0x01, 0x11, 0x04, 0x04, 0x12, 0x01, 0x04, 0x12, 0x01, 0x01, 0x02, 0x01, 0x01, 0x05, 0x10,  // 0xD0
    0x02, 0x0B, 0x03, 0x00, 0x04, 0x0E, 0x0D, 0x0F, 0x06, 0x07, 0x08, 0x09, 0x0C,  // 0xE0
};
inline uint8_t KindOfCategory(uint8_t category) {
    return category < sizeof(WEAPON_KIND_TABLE) ? WEAPON_KIND_TABLE[category]
                                                : WEAPON_KIND_NONE;
}
// Weapons whose shape follows the attack state. Each tick the weapon update
// 0x5E7DEC reads the owner's attack state (0x5E7F6C) and calls the class
// virtual +0xD0 (attacking) or +0xD4 (not attacking). Most classes leave
// both as the no-op 0x61CDB0; the rest move their own fields past the
// 0x240-byte base object toward an attack and an idle value (Blade Dance's
// blade extension, Slicer of Assassin's fold and length, claws opening,
// parasols, spinning parts), which their draw turns into the shape. The
// trail endpoints are authored for the attack shape.
constexpr uintptr_t WEAPON_VT_ATTACKING = 0xD0;
constexpr uintptr_t WEAPON_VT_IDLE = 0xD4;
constexpr uintptr_t WEAPON_VT_NOOP = 0x0061CDB0;
constexpr uintptr_t WEAPON_VARIANT_OFFSET = 0xF4;   // item data[2]
// Whether an item of a class with its own attacking / idle pair changes
// shape. Most pairs act on every item; these act on some (each pair's
// condition, keyed on its attacking virtual):
inline bool PairReshapes(uintptr_t attacking_fn, uint8_t category, uint8_t variant) {
    switch (attacking_fn) {
    case 0x005EC534:  // daggers: variants 5 and 8 (Blade Dance, Zero Divide)
        return variant == 5 || variant == 8;
    case 0x005FA15C:  // partisans: category 4 variant 5 (Brionac)
        return category == 0x04 && variant == 5;
    case 0x005FD594:  // slicers: category 5 variants 5 and 7
        return category == 0x05 && (variant == 5 || variant == 7);
    case 0x005FB2A8:  // rifles: category 7 variant 5
        return category == 0x07 && variant == 5;
    case 0x005ECF44:  // wands: variant 7
        return variant == 7;
    case 0x00600F6C:  // canes: category 0x0A variant 5 (+0x244 there is a
                      // once-per-attack sound latch, not shape)
        return category == 0x0A && variant == 5;
    case 0x005FE864:  // category 0x14 variant 2 (its motion speed)
        return category == 0x14 && variant == 2;
    case 0x005EAF7C:  // category 0x8B: every variant but 3
        return variant != 3;
    default:
        return true;
    }
}
// The weapon object's flags (+0x1DC): bit 0x400 = the held draw 0x5E8088
// takes its two-pass path, drawing the model on bone 48 and again on bone
// 35 (set by the class ctor: daggers, G-Assassin's Sabers, S-Beat's and
// S-Red's Blade, Lavis Blade, Twin Chakram ...): one half per hand.
constexpr uintptr_t WEAPON_FLAGS_OFFSET = 0x1DC;
constexpr uint32_t WEAPON_FLAG_TWO_PASS = 0x400;
inline bool KindIsGun(uint8_t kind) {
    return kind == WEAPON_KIND_HANDGUN || kind == WEAPON_KIND_RIFLE ||
           kind == WEAPON_KIND_MECHGUN || kind == WEAPON_KIND_SHOT ||
           kind == WEAPON_KIND_LAUNCHER;
}
// Which kinds are two-handers. Single-hand weapons with animated parts
// (slicers, claws, double sabers) drift like an off-hand half, so the
// funnel split is gated by kind. Funnel duals (both halves in one
// bracket): daggers and knuckles. Mechguns and twin swords (e.g. Musashi
// 0x89, Jizai 0xB8, TypeSS 0xE7) draw one half per composite bracket; the
// attach bone assigns those (IsLeftArmBone), and this kind test gates the
// left hand's swing.
inline bool KindSplitsFunnel(uint8_t kind) {
    return kind == WEAPON_KIND_DAGGER || kind == WEAPON_KIND_KNUCKLE;
}
inline bool KindSplitsComposite(uint8_t kind) {
    return kind == WEAPON_KIND_MECHGUN || kind == WEAPON_KIND_TWIN_SWORD;
}
// Per-class fire override at vtbl+0xCC (weapon vtables are 0x100 bytes,
// fixed layout; +0xC8 = the base per-bullet fire virtual 0x5E6578, +0xCC
// = the class's override, the no-op stub 0x61CDB0 for plain guns). Melee
// classes can have real overrides too (saber 0x5FBFE0), so this is a
// known list, complete for this client: every entry calls the base fire
// virtual or a fire sibling. Diagnostic only: the weapon-change log
// compares this older rule with the kind test.
constexpr uintptr_t WEAPON_FIRE_OVERRIDE_OFFSET = 0xCC;
constexpr uintptr_t FIRING_OVERRIDES[] = {
    0x005F8338,  // Spread Needle (class 0x12) + S-rank NEEDLE (0x7F)
    0x005F4620,  // mechgun family, class 0x08 (psobbvr_gunfire.hpp)
    0x006018AC,  // Yasminkov 9000M (class 0x6C)
    0x005EC2BC,  // the shared dual-fire base (Guld Milla 0x4B)
    // The shot family and friends, all projectile 0.
    0x005FE004,  // plain shots, class 0x09 (Shot .. Final Impact) + TypeSH/SHOT
                 // (0xEB): 5 barrels, base fire virtual once per hit pair
    0x005F7E08,  // S-rank SHOT (0x78): same 5-barrel shape
    0x005EBCFC,  // Belra Cannon (0x4D): fire sibling 0x5E6A88 + base virtual
    0x005F2C6C,  // Baranz Launcher (0x67): base virtual x4
    0x005F8D44,  // Dark Meteor (0x9E): own beam spawn from 5 muzzle transforms
    0x005FB6CC,  // Rocket Punch (0x47, mechgun kind): base virtual x2
    0x005F7194,  // S-rank PUNCH (0x84, mechgun kind): same shape
};
inline bool IsKnownFiringOverride(uintptr_t ov) {
    for (uintptr_t k : FIRING_OVERRIDES)
        if (k == ov)
            return true;
    return false;
}
// Photon swing trails. The weapon holds up to four trail objects in slots
// +0x1B0..+0x1BC (vtable 0xB10330; 0x5E7648 creates one for each endpoint
// byte +0x1C0+i that is not -1). Right after drawing the model, the held
// draw 0x5E8088 and the per-slot helper 0x5E6254 (called by the class draw
// overrides, twin swords 0x5F57AC among them) sample two points per slot
// with 0x5E83C8 - a weapon node from the owner's node matrices
// [entity+0xEBC], or the owner's hand bone - and pass them to the add
// routine 0x5E9CB8 (thiscall on the trail object). Both sample sites run
// only while the owner's action-state mask [entity+0x328] (1 << state,
// written by 0x694390) has an attack-state bit (states 5-7). The trail
// renders through 0x5E9B9C (untextured world-space strips, helper
// 0x82B284), called per slot by 0x5E87EC.
//
// The sampled points come from the game's arm animation, which the
// re-seat replaces, so the add hook moves them with the transform the
// last re-seated part got, and keeps a sample only while the blade moves
// fast in room space. To sample outside attacks as well, the owner's
// action mask carries an attack bit while the sample sites run; the
// model draw and everything after see the real value. A weapon whose
// shape follows the attack state (PairReshapes) never gets it: its trail
// shows during attacks only, as in the original game.
constexpr uintptr_t TRAIL_RENDER = 0x005E9B9C;
constexpr uintptr_t TRAIL_ADD = 0x005E9CB8;
constexpr uintptr_t TRAIL_SLOT_SAMPLE = 0x005E6254;
constexpr uintptr_t WEAPON_TRAIL_SLOT_FIRST = 0x1B0;
constexpr int WEAPON_TRAIL_SLOT_COUNT = 4;
// Trail object (ctor 0x5E9A70): +0x1C vertex buffer, +0x20 vertex count
// (the add 0x5E9CB8 smooths from the newest pair while it is nonzero).
constexpr uintptr_t TRAIL_VERTEX_COUNT_OFFSET = 0x20;
constexpr uintptr_t WEAPON_OWNER_OFFSET = 0xF8;          // the owner entity
constexpr uintptr_t ENTITY_ACTION_MASK_OFFSET = 0x328;
constexpr uint32_t ACTION_MASK_ATTACKING = 0xE0;         // states 5-7
constexpr uint32_t ACTION_MASK_ATTACK = 0x20;            // state 5
// A trail stops when the blade slows below this share of
// weapon_trail_speed.
constexpr float TRAIL_STOP_RATIO = 0.5f;
// Composite weapons (twin swords, mechguns and the other two-model
// classes) draw through a second entry into the held-model draw code,
// 0x5E84A8 (thiscall on the weapon object). The twin-sword draw override
// (0x5F57AC) calls it once per half: model [this+0xFC] on bone 0x30 (48),
// then the second model swapped in from [this+0x1AC] on bone 0x23 (35).
constexpr uintptr_t WEAPON_COMP_DRAW = 0x005E84A8;
// Twin split thresholds: a part's translation drift from its first-seen
// position relative to the bracket root, in game units (same-hand parts
// hold within +-0.002; the off-hand half drifts even at idle).
constexpr int TWIN_MAX_PARTS = 32;
constexpr float TWIN_DEV_HIGH = 0.08f;    // any part crossing this arms the latch
constexpr float TWIN_DEV_LOW = 0.015f;    // cluster membership at latch time
constexpr int TWIN_SETTLE_BRACKETS = 16;  // extra brackets after the first cross

using DrawFn = void(__fastcall*)(void* self, void* edx);
using TrailAddFn = void(__fastcall*)(void* self, void* edx, float* a, float* b);
using TrailSampleFn = void(__fastcall*)(void* self, void* edx, int slot);
inline DrawFn original_draw = nullptr;
inline DrawFn original_comp_draw = nullptr;
inline DrawFn original_trail_render = nullptr;
inline TrailAddFn original_trail_add = nullptr;
inline TrailSampleFn original_trail_sample = nullptr;
inline bool installed = false;

// Per-pass state (reset in OnFrame).
inline void* current_weapon = nullptr;  // [entity+0xE10], validated per pass
inline uint8_t current_category = 0;    // weapon item data[1] (byte +0xF3)
inline uint8_t current_kind = WEAPON_KIND_NONE;  // WEAPON_KIND_TABLE[category]
inline bool current_is_gun = false;     // KindIsGun(current_kind)
inline bool current_twin_funnel = false;  // the funnel learner may latch a split
inline bool current_twin_comp = false;    // a mechgun or twin-sword kind
inline uint8_t current_variant = 0;       // item data[2] (+0xF4), logged
inline uintptr_t current_attacking_fn = 0;  // vtbl+0xD0, logged
inline uint8_t current_projectile = 0;  // the PMT projectile byte (diagnostic)
inline uintptr_t current_fire_override = 0;  // vtbl+0xCC of the weapon object
// The swing gates' weapon test: a melee weapon, or bare hands with
// [vr] swing_unarmed (punches run the same attack state machine).
inline bool SwingWeapon() {
    if (current_weapon == nullptr)
        return vrmod::config.swing_unarmed;
    return !current_is_gun;
}
inline void* logged_weapon = reinterpret_cast<void*>(~uintptr_t(0));  // last classification logged
inline bool bracket_open = false;       // inside the weapon object's draw
inline bool bracket_is_left = false;    // this bracket = the off-hand half
inline bool bracket_learns = false;     // funnel bracket: twin-split learning runs
inline bool have_grip = false;          // grip_world resolved this pass
// The character's hand bone (the weapon seat and the hands' frame): the
// entity's bone matrix array at entity+0xE0 (64 bytes per bone);
// bone[hand_bone_index] x the global root matrix [0xA48980] = the hand's
// world matrix. Bone 48 on every model checked; hands.hpp re-confirms.
constexpr uintptr_t ENTITY_BONES_OFFSET = 0xE0;
constexpr uintptr_t GLOBAL_ROOT_MATRIX = 0x00A48980;
inline int hand_bone_index = 48;
inline bool ArrayBoneWorld(int i, D3DMATRIX& out) {
    const uintptr_t entity = gamecam::ResolveEntity();
    if (entity == 0 || !diag::Accessible(entity + ENTITY_BONES_OFFSET, 4, false))
        return false;
    const uintptr_t bones = *reinterpret_cast<const uintptr_t*>(entity + ENTITY_BONES_OFFSET);
    const uintptr_t m = bones + (uintptr_t)i * 64;
    if (bones == 0 || i < 0 || !diag::Accessible(m, 64, false) ||
        !diag::Accessible(GLOBAL_ROOT_MATRIX, 64, false))
        return false;
    out = vrmod::Multiply(*reinterpret_cast<const D3DMATRIX*>(m),
                          *reinterpret_cast<const D3DMATRIX*>(GLOBAL_ROOT_MATRIX));
    return true;
}
// Rigid delta between two world matrices: translation distance and the
// rotation angle of a x inverse(b).
inline void RigidDelta(const D3DMATRIX& a, const D3DMATRIX& b, float& dist, float& deg) {
    const D3DMATRIX d = vrmod::Multiply(a, vrmod::RigidInverse(b));
    dist = sqrtf(d._41 * d._41 + d._42 * d._42 + d._43 * d._43);
    float c = (d._11 + d._22 + d._33 - 1.0f) * 0.5f;
    if (c > 1.0f) c = 1.0f;
    if (c < -1.0f) c = -1.0f;
    deg = acosf(c) * 180.0f / 3.14159265f;
}
// The main-hand bracket's raw first matrix this pass, for the hands'
// bone-index check (it is the hand bone when the first node is inert).
inline D3DMATRIX bracket_root_raw = vrmod::Identity();
inline bool have_bracket_root_raw = false;
inline void* seat_logged_weapon = nullptr;   // one seat line per weapon
inline void* seat_logged_left = nullptr;     // one off-hand seat line per weapon
// An attach bone further than this from the first matrix is the wrong
// bone for this model: seat on the first matrix instead.
constexpr float SEAT_BONE_MAX_UNITS = 12.0f;
// The weapon's attach bone: signed byte +0x189 on the equipment object
// (getter 0x5D2450, setter 0x5D240C). The held-model draw 0x5E84A8 reads
// it at 0x5E8505 and parents the model to [owner+0xE0] + 64 * index (then,
// if the index matches a byte at +0x210/+0x211, shifts by the vec3 at
// +0x214/+0x220). 0x5E8088 forces bone 48 only on its photon-blade path
// (flag [this+0x1DC] bit 0x400). Most claws store 0x31 (49), a mount on
// the forearm (the ctor 0x5E959C sets it for the S-rank claws), so the
// seat uses this byte; a weapon off the hand bone is held at that bone's
// neutral-pose relation to the hand (NeutralRelation) plus the fist_*
// trim, which the hand mesh does not ride.
constexpr uintptr_t WEAPON_ATTACH_BONE_OFFSET = 0x189;
inline int seat_attach_bone = -1;     // the attach bone at the last main-hand bracket
inline bool seat_on_fist = false;     // that bone is not the hand bone
inline int ReadAttachBone() {
    const uintptr_t w = reinterpret_cast<uintptr_t>(current_weapon);
    if (w == 0 || !diag::Accessible(w + WEAPON_ATTACH_BONE_OFFSET, 1, false))
        return -1;
    return *reinterpret_cast<const int8_t*>(w + WEAPON_ATTACH_BONE_OFFSET);
}
// The shared skeleton's left arm is bones 26-37 (34 hand, 35 grip point,
// 36 / 37 attachment points) and the right arm 39-50; each left bone is
// its right mirror minus 13. Every draw of an off-hand half sets the
// attach bone to a left-arm bone around that half's 0x5E84A8 call: most
// class draws through 0x5E6334(35) (twin swords 0x5F57AC, Wok and
// S-Berill's Hands 0x5EEEA8, Sacred Duster 0x5FCC54), Panther's Claw
// 0x5EE3DC (34), Heart of Poumn 0x5F594C (36), the knuckles' 0x5F2EFC (the
// stored bone minus 13), the mechguns' 0x5E74EC (35). A weapon stores 48
// (the weapon slot's entry in the default table 0x9CB9AC) or 49 (the
// S-rank claws' ctor), so a left-arm bone marks the off-hand half.
constexpr int LEFT_ARM_BONE_FIRST = 26;
constexpr int LEFT_ARM_BONE_LAST = 37;
constexpr int MIRROR_BONE_OFFSET = 13;
inline bool IsLeftArmBone(int bone) {
    return bone >= LEFT_ARM_BONE_FIRST && bone <= LEFT_ARM_BONE_LAST;
}
// This weapon has drawn an off-hand half; reset on a weapon change.
inline bool draws_left_half = false;
inline D3DMATRIX grip_world = vrmod::Identity();  // grip_offset x hand-in-world
// The same plus the fist_* trim, for a weapon on the fist bone.
inline D3DMATRIX grip_world_fist = vrmod::Identity();
// A weapon on another bone than the hand. Bone 49, the claws' bone, is a
// mount on the forearm (child of the forearm bone 42 in the shared
// skeleton; the hand bone 48 hangs off the wrist 44 / 45), so its live
// relation to the hand changes with every wrist bend of the animation.
// The seat uses the relation in the model's neutral pose instead: the body
// tree [entity+0x34] walked in bone order (node, children, then siblings -
// the order of the bone array [entity+0xE0]) and composed from each node's
// stored transform. part x inverse(attach bone) x neutral(attach bone x
// inverse(hand bone)) x grip places the weapon on the VR hand as on a
// straight wrist, the same on every equip.
constexpr uintptr_t ENTITY_TREE_OFFSET = 0x34;
// Ninja object node: +0 eval flags (bit 0 = no translation, 1 = no
// rotation, 2 = no scale, 0x20 = rotate Z, X, Y instead of X, Y, Z), +8
// position f32[3], +0x14 angle i32[3] (65536 per turn), +0x20 scale
// f32[3], +0x2C child, +0x30 sibling.
constexpr uintptr_t NODE_SIZE = 0x34;
constexpr int NEUTRAL_BONE_COUNT = 64;
struct NeutralPose {
    uintptr_t entity = 0, tree = 0;
    int count = 0;                      // nodes walked
    D3DMATRIX world[NEUTRAL_BONE_COUNT];
    int parent[NEUTRAL_BONE_COUNT];
};
inline NeutralPose neutral;
inline void* neutral_logged_weapon = nullptr;  // one check line per weapon
// One node's local transform: scale, rotation (X, Y, Z or Z, X, Y), then
// translation, row-vector like the game's matrix stack.
inline D3DMATRIX NodeLocal(uintptr_t node) {
    const uint32_t flags = *reinterpret_cast<const uint32_t*>(node);
    const float* pos = reinterpret_cast<const float*>(node + 0x08);
    const int32_t* ang = reinterpret_cast<const int32_t*>(node + 0x14);
    const float* scl = reinterpret_cast<const float*>(node + 0x20);
    D3DMATRIX m = vrmod::Identity();
    if ((flags & 4) == 0) {
        m._11 = scl[0];
        m._22 = scl[1];
        m._33 = scl[2];
    }
    if ((flags & 2) == 0) {
        const float k = 2.0f * 3.14159265f / 65536.0f;
        auto rot = [&](int axis) {
            const float a = (float)ang[axis] * k, c = cosf(a), s = sinf(a);
            D3DMATRIX r = vrmod::Identity();
            if (axis == 0) {
                r._22 = c; r._23 = s; r._32 = -s; r._33 = c;
            } else if (axis == 1) {
                r._11 = c; r._13 = -s; r._31 = s; r._33 = c;
            } else {
                r._11 = c; r._12 = s; r._21 = -s; r._22 = c;
            }
            m = vrmod::Multiply(m, r);
        };
        if ((flags & 0x20) != 0) {
            rot(2); rot(0); rot(1);
        } else {
            rot(0); rot(1); rot(2);
        }
    }
    if ((flags & 1) == 0) {
        m._41 += pos[0];
        m._42 += pos[1];
        m._43 += pos[2];
    }
    return m;
}

// The local player's neutral pose, rebuilt when the entity or its tree
// changes. False if the tree cannot be read.
inline bool BuildNeutralPose() {
    const uintptr_t entity = gamecam::ResolveEntity();
    if (entity == 0 || !diag::Accessible(entity + ENTITY_TREE_OFFSET, 4, false))
        return false;
    const uintptr_t tree = *reinterpret_cast<const uintptr_t*>(entity + ENTITY_TREE_OFFSET);
    if (tree == 0)
        return false;
    if (entity == neutral.entity && tree == neutral.tree)
        return neutral.count > 0;
    neutral.entity = entity;
    neutral.tree = tree;
    neutral.count = 0;
    struct Pending {
        uintptr_t node;
        int parent;
    };
    Pending stack[2 * NEUTRAL_BONE_COUNT];
    int top = 0;
    stack[top++] = {tree, -1};
    while (top > 0 && neutral.count < NEUTRAL_BONE_COUNT) {
        const Pending p = stack[--top];
        if (!diag::Accessible(p.node, NODE_SIZE, false)) {
            neutral.count = 0;
            return false;
        }
        const int idx = neutral.count++;
        const D3DMATRIX local = NodeLocal(p.node);
        neutral.world[idx] = p.parent >= 0 ? vrmod::Multiply(local, neutral.world[p.parent]) : local;
        neutral.parent[idx] = p.parent;
        // The whole subtree before the sibling: push the sibling first.
        const uintptr_t child = *reinterpret_cast<const uintptr_t*>(p.node + 0x2C);
        const uintptr_t sibling = *reinterpret_cast<const uintptr_t*>(p.node + 0x30);
        if (sibling != 0 && top < 2 * NEUTRAL_BONE_COUNT)
            stack[top++] = {sibling, p.parent};
        if (child != 0 && top < 2 * NEUTRAL_BONE_COUNT)
            stack[top++] = {child, idx};
    }
    return neutral.count > 0;
}

// The inverse of an affine row-vector matrix (the tree may carry scale).
inline D3DMATRIX AffineInverse(const D3DMATRIX& m) {
    const float a = m._11, b = m._12, c = m._13, d = m._21, e = m._22, f = m._23,
                g = m._31, h = m._32, i = m._33;
    const float det = a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g);
    const float inv = det != 0.0f ? 1.0f / det : 0.0f;
    D3DMATRIX r = vrmod::Identity();
    r._11 = (e * i - f * h) * inv;
    r._12 = (c * h - b * i) * inv;
    r._13 = (b * f - c * e) * inv;
    r._21 = (f * g - d * i) * inv;
    r._22 = (a * i - c * g) * inv;
    r._23 = (c * d - a * f) * inv;
    r._31 = (d * h - e * g) * inv;
    r._32 = (b * g - a * h) * inv;
    r._33 = (a * e - b * d) * inv;
    r._41 = -(m._41 * r._11 + m._42 * r._21 + m._43 * r._31);
    r._42 = -(m._41 * r._12 + m._42 * r._22 + m._43 * r._32);
    r._43 = -(m._41 * r._13 + m._42 * r._23 + m._43 * r._33);
    return r;
}

// bone x inverse(base) in the neutral pose.
inline bool NeutralRelation(int bone, int base, D3DMATRIX& out) {
    if (!BuildNeutralPose() || bone < 0 || base < 0 || bone >= neutral.count ||
        base >= neutral.count)
        return false;
    out = vrmod::Multiply(neutral.world[bone], AffineInverse(neutral.world[base]));
    return true;
}

// One line per weapon: the neutral relation to the hand next to the live
// one, and a check of the walk - the attach bone against its parent, live
// and neutral (equal when the animation leaves that joint alone).
inline void LogNeutralCheck(int bone, const D3DMATRIX& bone_live, const D3DMATRIX& hand_live,
                            bool neutral_ok) {
    float live_d = 0.0f, live_deg = 0.0f;
    RigidDelta(bone_live, hand_live, live_d, live_deg);
    if (!neutral_ok) {
        diag::Log("seatbone: bone %d - no neutral pose (tree unreadable), live relation used "
                  "(%.2f units / %.1f deg from the hand bone)", bone, live_d, live_deg);
        return;
    }
    D3DMATRIX rel;
    NeutralRelation(bone, hand_bone_index, rel);
    const float neutral_d = sqrtf(rel._41 * rel._41 + rel._42 * rel._42 + rel._43 * rel._43);
    float c = (rel._11 + rel._22 + rel._33 - 1.0f) * 0.5f;
    c = c > 1.0f ? 1.0f : (c < -1.0f ? -1.0f : c);
    const float neutral_deg = acosf(c) * 180.0f / 3.14159265f;
    const int parent = neutral.parent[bone];
    float check_d = -1.0f, check_deg = -1.0f;
    D3DMATRIX parent_live, local_neutral;
    if (parent >= 0 && ArrayBoneWorld(parent, parent_live) &&
        NeutralRelation(bone, parent, local_neutral)) {
        const D3DMATRIX local_live = vrmod::Multiply(bone_live, vrmod::RigidInverse(parent_live));
        RigidDelta(local_live, local_neutral, check_d, check_deg);
    }
    diag::Log("seatbone: bone %d held at its neutral pose: %.2f units / %.1f deg from the hand "
              "bone (live now %.2f / %.1f); walk check vs parent %d: %.3f units / %.2f deg "
              "(%d nodes)", bone, neutral_d, neutral_deg, live_d, live_deg, parent, check_d,
              check_deg, neutral.count);
}
inline int part_index = 0;              // matrix # within the current bracket
inline D3DMATRIX root_inv = vrmod::Identity();  // inverse of the bracket's first matrix
// Twin split state, learned per weapon: parts rigid to the bracket root
// are the main hand; a contiguous tail of drifting parts is the off-hand
// half, re-seated onto the left grip rooted at its own first matrix.
inline void* learn_weapon = nullptr;    // weapon the learn state belongs to
inline bool learn_valid = false;        // baseline rel captured (first bracket)
inline int learn_count = -1;            // part count (order-stable, must hold)
inline float first_rel[TWIN_MAX_PARTS][3] = {};  // baseline rel translations
inline float max_dev[TWIN_MAX_PARTS] = {};       // max drift from baseline
inline int settle = -1;                 // brackets left before latching
inline int split_index = -1;            // first off-hand part; -1 = single-hand
inline D3DMATRIX left_root_inv = vrmod::Identity();
inline bool have_left_grip = false;     // grip_world_left resolved this pass
inline D3DMATRIX grip_world_left = vrmod::Identity();
// The same plus the fist_* trim, for an off-hand half on another bone than
// the left grip point.
inline D3DMATRIX grip_world_left_fist = vrmod::Identity();
inline bool left_on_fist = false;       // this off-hand bracket's bone is not the grip point
// Diagnostics (a short log window after the grip is switched on).
inline int log_budget = 0;
inline bool prev_enabled = false;
inline bool bracket_fired_last_pass = false;
inline int subst_sets_last_pass = 0;
inline bool bracket_fired = false;
// A bracket set at least one matrix this pass (the weapon drew). In towns
// the bracket opens every pass but sets nothing (holstered).
inline bool bracket_drew = false;
inline bool bracket_drew_last_pass = false;
inline int subst_sets = 0;
inline int subst_sets_left = 0;         // off-hand re-seats this pass
inline int subst_sets_left_last_pass = 0;
inline int trails_suppressed = 0;       // trail renders skipped this pass
inline int trails_suppressed_last_pass = 0;
// Photon trails (see TRAIL_ADD). The transform the last re-seated part
// got (point' = point x trail_map) and its hand, for the trail points
// sampled right after that part's draw.
inline D3DMATRIX trail_map = vrmod::Identity();
inline int trail_map_hand = -1;         // 0 left, 1 right, -1 none this pass
// Room space from world (the inverse of gamecam::WorldFromTracking).
inline D3DMATRIX trail_room_from_world = vrmod::Identity();
inline bool have_trail_room = false;
// The owner's action mask while it carries the forced attack bit.
inline uint32_t* trail_mask = nullptr;
inline uint32_t trail_mask_saved = 0;
inline uintptr_t current_owner = 0;     // the local player entity, per pass
struct TrailSlot {
    float prev[2][3] = {};              // room-space endpoints (m)
    LONGLONG prev_qpc = 0;
    bool prev_valid = false;
    int hand = -1;                      // the hand of the last sample
    bool on = false;                    // fast enough: samples are kept
};
inline TrailSlot trail_slots[WEAPON_TRAIL_SLOT_COUNT];
inline LONGLONG trail_qpf = 0;
// The weapon's shape follows the attack state (PairReshapes), so its trail
// is not sampled outside attacks. Set per pass in OnFrame.
inline bool trail_reshapes = false;
inline bool trail_logged = false;       // first kept sample logged (per weapon)
inline int trail_kept = 0;              // samples kept / dropped this pass
inline int trail_dropped = 0;           // (totals: diag::trail_*)
// Hand-bone stash keep-alive: passes since a held-weapon bracket last
// fired - see the validity block in OnFrame.
inline int passes_since_bracket = 100;

// True while draws belong to the re-seated weapon: the draw paths skip
// head-trim suppression and body culling (a raised weapon can sit inside
// the head sphere).
inline bool ExemptingDraws() {
    return bracket_open && (have_grip || have_left_grip);
}

// grip_offset: rotation + translation in grip-local axes, labelled as the
// wearer feels them. Held thumb-up, the grip frame's -Z points up along
// the fist and the weapon extends along Y: pitch (tip up/down) = about X,
// roll (spin about the blade) = about Y, yaw (left/right) = about Z.
// Applied Rx*Ry*Rz (row-vector), then fwd_cm along -Z, up_cm along +Y,
// side_cm along +X (through the palm); cm scaled by world_scale.
inline D3DMATRIX GripOffsetMatrix(float pitch_deg, float roll_deg,
                                  float yaw_deg, float fwd_cm, float up_cm,
                                  float side_cm = 0.0f) {
    const float d2r = 3.14159265f / 180.0f;
    // Negated so positive pitch tips the blade/barrel up.
    const float p = -pitch_deg * d2r;
    const float ang_y = roll_deg * d2r;  // felt roll = about Y
    const float ang_z = yaw_deg * d2r;   // felt yaw = about Z
    D3DMATRIX rx = vrmod::Identity(), ry = vrmod::Identity(), rz = vrmod::Identity();
    rx._22 = cosf(p); rx._23 = sinf(p); rx._32 = -sinf(p); rx._33 = cosf(p);
    ry._11 = cosf(ang_y); ry._13 = -sinf(ang_y); ry._31 = sinf(ang_y); ry._33 = cosf(ang_y);
    rz._11 = cosf(ang_z); rz._12 = sinf(ang_z); rz._21 = -sinf(ang_z); rz._22 = cosf(ang_z);
    D3DMATRIX m = vrmod::Multiply(vrmod::Multiply(rx, ry), rz);
    const float cm = 0.01f * vrmod::config.world_scale;
    m._41 = side_cm * cm;
    m._42 = up_cm * cm;
    m._43 = -fwd_cm * cm;
    return m;
}

// The active tuple: guns have their own, separate from melee.
// The fist_* trim, for a weapon on another bone than its hand's grip point.
inline D3DMATRIX FistTrim() {
    return GripOffsetMatrix(vrmod::config.fist_pitch_deg, vrmod::config.fist_roll_deg,
                            vrmod::config.fist_yaw_deg, vrmod::config.fist_fwd_cm,
                            vrmod::config.fist_up_cm, vrmod::config.fist_side_cm);
}

inline D3DMATRIX ActiveGripOffset() {
    if (current_is_gun)
        return GripOffsetMatrix(vrmod::config.gun_pitch_deg,
                                vrmod::config.gun_roll_deg,
                                vrmod::config.gun_yaw_deg,
                                vrmod::config.gun_fwd_cm,
                                vrmod::config.gun_up_cm);
    return GripOffsetMatrix(vrmod::config.grip_pitch_deg,
                            vrmod::config.grip_roll_deg,
                            vrmod::config.grip_yaw_deg,
                            vrmod::config.grip_fwd_cm,
                            vrmod::config.grip_up_cm);
}

// A hand's barrel ray (origin, unit forward, world units): the -Y axis
// (muzzle end) of the frame the gun is drawn in, grip tuple x hand world
// pose, so the ray is the visible barrel. pitch_trim_deg tilts it about
// the weapon's side axis, positive = toward world down. Works for either
// hand (the grip frames and tuples are mirror-symmetric). False with no
// pose or before the head pose is written this frame.
inline bool BarrelRay(int hand, float* origin, float* fwd,
                      float pitch_trim_deg) {
    D3DMATRIX pose, hand_world;
    if (!vrmod::Get()->GetHandPose(hand & 1, pose) ||
        !gamecam::WorldFromTracking(pose, hand_world))
        return false;
    const D3DMATRIX m = vrmod::Multiply(ActiveGripOffset(), hand_world);
    float f[3] = {-m._21, -m._22, -m._23};  // row 2 = the weapon's Y axis; muzzle on -Y
    float len = sqrtf(f[0] * f[0] + f[1] * f[1] + f[2] * f[2]);
    if (len < 1e-6f)
        return false;
    f[0] /= len; f[1] /= len; f[2] /= len;
    if (pitch_trim_deg != 0.0f) {
        // Side axis = row 1 (the weapon's X). t = side x fwd, signed so
        // positive trim tilts toward world down (-Y).
        float ax[3] = {m._11, m._12, m._13};
        const float al = sqrtf(ax[0] * ax[0] + ax[1] * ax[1] + ax[2] * ax[2]);
        if (al > 1e-6f) {
            ax[0] /= al; ax[1] /= al; ax[2] /= al;
            float t[3] = {ax[1] * f[2] - ax[2] * f[1],
                          ax[2] * f[0] - ax[0] * f[2],
                          ax[0] * f[1] - ax[1] * f[0]};
            if (t[1] > 0.0f) {
                t[0] = -t[0]; t[1] = -t[1]; t[2] = -t[2];
            }
            const float a = pitch_trim_deg * (3.14159265f / 180.0f);
            const float c = cosf(a), s = sinf(a);
            for (int i = 0; i < 3; i++)
                f[i] = f[i] * c + t[i] * s;
        }
    }
    fwd[0] = f[0]; fwd[1] = f[1]; fwd[2] = f[2];
    origin[0] = m._41; origin[1] = m._42; origin[2] = m._43;
    return true;
}

inline void ResetLearning() {
    learn_valid = false;
    learn_count = -1;
    settle = -1;
    split_index = -1;
    for (int i = 0; i < TWIN_MAX_PARTS; i++)
        max_dev[i] = 0.0f;
}

// Shared by both bracket hooks (funnel + composite entry). Returns whether
// this call owns the bracket (nested calls fold into the outer bracket).
inline bool BracketOpen(void* self, const char* which, bool left,
                        bool learns) {
    if (bracket_open)
        return false;
    bracket_open = true;
    bracket_is_left = left;
    bracket_learns = learns;
    bracket_fired = true;
    part_index = 0;
    return true;
}

inline void BracketClose() {
    bracket_open = false;
    // Twin-split learning, once per completed funnel bracket (composite
    // brackets split per bracket instead).
    if (!bracket_learns || !vrmod::config.twin_split || !current_twin_funnel ||
        split_index >= 0)
        return;
    if (!learn_valid) {
        if (part_index > 0) {
            learn_count = part_index;
            learn_valid = true;
        }
    } else if (part_index > 0 && part_index != learn_count) {
        // Part count changed (equip transition, effects): relearn.
        ResetLearning();
    } else if (settle >= 0 && settle-- == 0) {
        // Latch: walk back from the last part while it kept moving (the
        // off-hand half is a contiguous tail; part 0 never counts).
        int j = learn_count;
        while (j > 1 && max_dev[j - 1] > TWIN_DEV_LOW)
            j--;
        if (j > 1 && j < learn_count) {
            split_index = j;
            diag::Log("weapongrip: twin split latched at part %d of %d "
                      "(dev: %.3f %.3f %.3f %.3f %.3f %.3f)",
                      j, learn_count, max_dev[0], max_dev[1], max_dev[2],
                      max_dev[3], max_dev[4], max_dev[5]);
        } else {
            // No clean rigid head: not a twin (or not settled); start over.
            ResetLearning();
        }
    }
}

// The local weapon's trail slot holding this trail object, or -1.
inline int TrailSlotOf(void* trail) {
    if (trail == nullptr || current_weapon == nullptr)
        return -1;
    const uintptr_t w = reinterpret_cast<uintptr_t>(current_weapon);
    for (int i = 0; i < WEAPON_TRAIL_SLOT_COUNT; i++) {
        const uintptr_t slot = w + WEAPON_TRAIL_SLOT_FIRST + i * 4;
        if (diag::Accessible(slot, 4, false) &&
            trail == *reinterpret_cast<void* const*>(slot))
            return i;
    }
    return -1;
}

// Sampling outside attacks: a re-seated melee weapon with trails on. (Any
// re-seated weapon's samples move onto the hand - HookTrailAdd.)
inline bool TrailFromHand(void* weapon) {
    return vrmod::config.weapon_trail && have_grip && weapon != nullptr &&
           weapon == current_weapon && !current_is_gun;
}

// Gives the owner's action mask an attack bit for the sample sites, when
// it has none and the weapon keeps its shape outside attacks. Returns
// whether this call forced it (and must restore).
inline bool ForceTrailMask(void* weapon) {
    if (trail_mask != nullptr || trail_reshapes || !TrailFromHand(weapon))
        return false;
    const uintptr_t w = reinterpret_cast<uintptr_t>(weapon);
    if (!diag::Accessible(w + WEAPON_OWNER_OFFSET, 4, false))
        return false;
    const uintptr_t owner = *reinterpret_cast<const uintptr_t*>(w + WEAPON_OWNER_OFFSET);
    if (owner == 0 || owner != current_owner ||
        !diag::Accessible(owner + ENTITY_ACTION_MASK_OFFSET, 4, true))
        return false;
    uint32_t* const mask = reinterpret_cast<uint32_t*>(owner + ENTITY_ACTION_MASK_OFFSET);
    if ((*mask & ACTION_MASK_ATTACKING) != 0)
        return false;  // attacking: the game samples anyway
    trail_mask_saved = *mask;
    *mask = trail_mask_saved | ACTION_MASK_ATTACK;
    trail_mask = mask;
    return true;
}

inline void RestoreTrailMask() {
    if (trail_mask != nullptr)
        *trail_mask = trail_mask_saved;
    trail_mask = nullptr;
}

inline void __fastcall HookDraw(void* self, void* edx) {
    const bool owns = self != nullptr && self == current_weapon &&
                      BracketOpen(self, "funnel", false, true);
    const bool forced = ForceTrailMask(self);
    original_draw(self, edx);
    if (forced)
        RestoreTrailMask();
    if (owns)
        BracketClose();
}

// The composite entry: the held draw's two-pass path calls it inside its
// own bracket (folded in); the class draws (+0xD8) and the mechguns'
// 0x5E74EC call it once per half. A half drawn on a left-arm bone is the
// off hand.
inline void __fastcall HookCompDraw(void* self, void* edx) {
    bool owns = false;
    if (self != nullptr && self == current_weapon) {
        const bool left = vrmod::config.twin_split && IsLeftArmBone(ReadAttachBone());
        owns = BracketOpen(self, "comp", left, false);
        if (owns && left)
            draws_left_half = true;
    }
    // The model draw sees the real action mask; the held draw's samples
    // after it see the forced one again.
    uint32_t* const forced = trail_mask;
    if (forced != nullptr)
        *forced = trail_mask_saved;
    original_comp_draw(self, edx);
    if (forced != nullptr) {
        trail_mask_saved = *forced;
        *forced = trail_mask_saved | ACTION_MASK_ATTACK;
    }
    if (owns)
        BracketClose();
}

// The trail render: the local weapon's trails are hidden while the re-seat
// drives and trails are off (the game's ribbon follows the hidden arm).
inline void __fastcall HookTrailRender(void* self, void* edx) {
    if (!vrmod::config.weapon_trail && have_grip && TrailSlotOf(self) >= 0) {
        trails_suppressed++;
        return;
    }
    original_trail_render(self, edx);
}

inline void TransformPoint(const float p[3], const D3DMATRIX& m, float out[3]) {
    out[0] = p[0] * m._11 + p[1] * m._21 + p[2] * m._31 + m._41;
    out[1] = p[0] * m._12 + p[1] * m._22 + p[2] * m._32 + m._42;
    out[2] = p[0] * m._13 + p[1] * m._23 + p[2] * m._33 + m._43;
}

inline float Distance3(const float a[3], const float b[3]) {
    const float dx = a[0] - b[0], dy = a[1] - b[1], dz = a[2] - b[2];
    return sqrtf(dx * dx + dy * dy + dz * dz);
}

// Whether this slot's blade moves fast enough in room space for a trail:
// starts at weapon_trail_speed, stops below TRAIL_STOP_RATIO of it.
// Walking and turning move the world, not the room, so they never count.
inline bool TrailFast(int slot, const float wa[3], const float wb[3], float& speed) {
    TrailSlot& s = trail_slots[slot];
    const float ws = vrmod::config.world_scale;
    float ra[3], rb[3];
    TransformPoint(wa, trail_room_from_world, ra);
    TransformPoint(wb, trail_room_from_world, rb);
    for (int i = 0; i < 3; i++) {
        ra[i] /= ws;
        rb[i] /= ws;
    }
    LARGE_INTEGER qpc;
    QueryPerformanceCounter(&qpc);
    if (trail_qpf == 0) {
        LARGE_INTEGER f;
        QueryPerformanceFrequency(&f);
        trail_qpf = f.QuadPart;
    }
    speed = 0.0f;
    if (s.prev_valid) {
        const double dt = double(qpc.QuadPart - s.prev_qpc) / double(trail_qpf);
        if (dt < 0.005)
            return s.on;  // a second sample in the same tick
        if (dt < 0.25) {
            const float da = Distance3(ra, s.prev[0]);
            const float db = Distance3(rb, s.prev[1]);
            speed = (float)((da > db ? da : db) / dt);
            const float start = vrmod::config.weapon_trail_speed;
            s.on = s.on ? speed >= start * TRAIL_STOP_RATIO : speed >= start;
        } else {
            s.on = false;
        }
    } else {
        s.on = false;
    }
    for (int i = 0; i < 3; i++) {
        s.prev[0][i] = ra[i];
        s.prev[1][i] = rb[i];
    }
    s.prev_qpc = qpc.QuadPart;
    s.prev_valid = true;
    return s.on;
}

// The trail's add routine: the local weapon's samples move onto the
// re-seated weapon and are kept only on a fast swing. With no re-seat
// transform this pass the sample is dropped rather than drawn along the
// hidden arm.
inline void __fastcall HookTrailAdd(void* self, void* edx, float* a, float* b) {
    const int slot = (a != nullptr && b != nullptr && vrmod::config.weapon_trail && have_grip)
                         ? TrailSlotOf(self) : -1;
    if (slot < 0) {
        original_trail_add(self, edx, a, b);
        return;
    }
    if (trail_map_hand < 0 || !have_trail_room) {
        trail_dropped++;
        return;
    }
    // A slot that changed hands (the twin split latching) jumped rather
    // than swung: restart its speed test and empty its ribbon, so the add's
    // smoothing does not bridge the two hands.
    TrailSlot& ts = trail_slots[slot];
    if (ts.prev_valid && ts.hand != trail_map_hand) {
        ts.prev_valid = false;
        ts.on = false;
        const uintptr_t t = reinterpret_cast<uintptr_t>(self);
        if (diag::Accessible(t + TRAIL_VERTEX_COUNT_OFFSET, 4, true))
            *reinterpret_cast<int*>(t + TRAIL_VERTEX_COUNT_OFFSET) = 0;
    }
    ts.hand = trail_map_hand;
    float wa[3], wb[3];
    TransformPoint(a, trail_map, wa);
    TransformPoint(b, trail_map, wb);
    float speed = 0.0f;
    if (!TrailFast(slot, wa, wb, speed)) {
        trail_dropped++;
        return;
    }
    trail_kept++;
    if (!trail_logged) {
        trail_logged = true;
        diag::Log("weapontrail: first trail sample kept (weapon %p slot %d, %s hand, %.2f m/s)",
                  current_weapon, slot, trail_map_hand == 0 ? "left" : "right", speed);
    }
    original_trail_add(self, edx, wa, wb);
}

// The per-slot sample helper the class draw overrides call: the forced
// attack bit for the length of the call.
inline void __fastcall HookTrailSample(void* self, void* edx, int slot) {
    const bool forced = ForceTrailMask(self);
    original_trail_sample(self, edx, slot);
    if (forced)
        RestoreTrailMask();
}

// weapon_scale: uniform scale about the weapon root (the point pinned to
// the controller), applied to the part's root-space matrix.
inline D3DMATRIX ScaleRel(D3DMATRIX rel, float s) {
    rel._11 *= s; rel._12 *= s; rel._13 *= s;
    rel._21 *= s; rel._22 *= s; rel._23 *= s;
    rel._31 *= s; rel._32 *= s; rel._33 *= s;
    rel._41 *= s; rel._42 *= s; rel._43 *= s;
    return rel;
}

// The re-seat of a world-space point, kept for the trail points sampled
// after this part's draw: point x inverse(root), scaled about the root,
// then onto the grip - the same steps as a part matrix.
inline void NoteTrailMap(const D3DMATRIX& inv, const D3DMATRIX& grip, int hand) {
    const D3DMATRIX scaled = vrmod::config.weapon_scale != 1.0f
                                 ? ScaleRel(inv, vrmod::config.weapon_scale) : inv;
    trail_map = vrmod::Multiply(scaled, grip);
    trail_map_hand = hand;
}

// Every device WORLD SetTransform on world-space passes. Returns true
// with the re-seated matrix in out.
inline bool SubstituteWorld(const D3DMATRIX& in, D3DMATRIX& out, bool boxed) {
    if (!bracket_open)
        return false;
    // A matrix at exactly the world origin opening a bracket is not a part
    // (Phoenix Claw sets one before its parts): left alone, and the next
    // matrix is the root.
    if (part_index == 0 && fabsf(in._41) < 1e-4f && fabsf(in._42) < 1e-4f &&
        fabsf(in._43) < 1e-4f)
        return false;
    const int i = part_index++;
    // Equipment part matrices are rigid, so RigidInverse is exact.
    // The seat root: the first matrix is hand bone x the model's first
    // node, which some weapons rotate (the basic Partisans, the parasols,
    // Glide Divine). So the main hand seats on the weapon's attach bone
    // (WEAPON_ATTACH_BONE_OFFSET) when readable and near the first matrix,
    // else on the first matrix.
    if (i == 0) {
        D3DMATRIX root = in;
        if (!bracket_is_left) {
            bracket_root_raw = in;
            have_bracket_root_raw = true;
            const int attach = ReadAttachBone();
            const int seat_index = attach >= 0 ? attach : hand_bone_index;
            seat_attach_bone = seat_index;
            seat_on_fist = seat_index != hand_bone_index;
            D3DMATRIX bone;
            bool seated_on_bone = false;
            if (ArrayBoneWorld(seat_index, bone)) {
                float dist = 0.0f, deg = 0.0f;
                RigidDelta(in, bone, dist, deg);
                seated_on_bone = dist <= SEAT_BONE_MAX_UNITS;
                if (seated_on_bone)
                    root = bone;
                if (seat_logged_weapon != current_weapon) {
                    seat_logged_weapon = current_weapon;
                    diag::Log("seatbone: attach bone %d%s; first matrix sits %.2f units / %.1f deg off it -> %s",
                              seat_index,
                              seat_on_fist ? " (NOT the hand bone - neutral pose + fist trim)" : " (the hand bone)",
                              dist, deg,
                              seated_on_bone ? "seating on the bone" : "too far, seating on the first matrix");
                }
            }
            // Hand-bone stash for the VR hands: the hand bone when the
            // weapon sits on another bone, else the seat root.
            D3DMATRIX hand;
            const bool have_hand =
                seat_on_fist && seated_on_bone && ArrayBoneWorld(hand_bone_index, hand);
            if (have_hand)
                vrmod::hand_bone_world_right = hand;
            else
                vrmod::hand_bone_world_right = root;
            vrmod::have_hand_bone_right = true;
            root_inv = vrmod::RigidInverse(root);
            // Off the hand bone: held at the neutral-pose relation to the
            // hand (the live one if the tree cannot be read).
            if (have_hand) {
                D3DMATRIX rel;
                const bool neutral_ok = NeutralRelation(seat_index, hand_bone_index, rel);
                if (!neutral_ok)
                    rel = vrmod::Multiply(root, vrmod::RigidInverse(hand));
                root_inv = vrmod::Multiply(root_inv, rel);
                if (neutral_logged_weapon != current_weapon) {
                    neutral_logged_weapon = current_weapon;
                    LogNeutralCheck(seat_index, root, hand, neutral_ok);
                }
            }
        } else {
            // The off-hand half, mirrored: seated on its attach bone; a half
            // off the left grip point (the hand bone's mirror) is held at
            // that bone's neutral-pose relation to it plus the fist_* trim.
            const int grip_bone = hand_bone_index - MIRROR_BONE_OFFSET;
            const int attach = ReadAttachBone();
            const int seat_index = attach >= 0 ? attach : grip_bone;
            left_on_fist = seat_index != grip_bone;
            D3DMATRIX bone;
            bool seated_on_bone = false;
            if (ArrayBoneWorld(seat_index, bone)) {
                float dist = 0.0f, deg = 0.0f;
                RigidDelta(in, bone, dist, deg);
                seated_on_bone = dist <= SEAT_BONE_MAX_UNITS;
                if (seated_on_bone)
                    root = bone;
                if (seat_logged_left != current_weapon) {
                    seat_logged_left = current_weapon;
                    diag::Log("seatbone: off-hand half on bone %d%s; first matrix sits %.2f units / %.1f deg off it -> %s",
                              seat_index,
                              left_on_fist ? " (NOT the left grip bone - neutral pose + fist trim)" : " (the left grip bone)",
                              dist, deg,
                              seated_on_bone ? "seating on the bone" : "too far, seating on the first matrix");
                }
            }
            D3DMATRIX hand;
            const bool have_hand =
                left_on_fist && seated_on_bone && ArrayBoneWorld(grip_bone, hand);
            // Composite off-hand brackets stash the left bone (the funnel
            // split stashes it at split_index below).
            vrmod::hand_bone_world_left = have_hand ? hand : root;
            vrmod::have_hand_bone_left = true;
            root_inv = vrmod::RigidInverse(root);
            if (have_hand) {
                D3DMATRIX rel;
                if (!NeutralRelation(seat_index, grip_bone, rel))
                    rel = vrmod::Multiply(root, vrmod::RigidInverse(hand));
                root_inv = vrmod::Multiply(root_inv, rel);
            }
        }
        bracket_drew = true;
    }
    // Twin-split learning (funnel brackets): track each part's drift from
    // its first-seen root-relative translation (part order is stable).
    if (bracket_learns && vrmod::config.twin_split && current_twin_funnel &&
        split_index < 0 && i < TWIN_MAX_PARTS && i > 0) {
        const D3DMATRIX rel = vrmod::Multiply(in, root_inv);
        if (!learn_valid) {
            first_rel[i][0] = rel._41;
            first_rel[i][1] = rel._42;
            first_rel[i][2] = rel._43;
        } else if (i < learn_count) {
            const float dx = rel._41 - first_rel[i][0];
            const float dy = rel._42 - first_rel[i][1];
            const float dz = rel._43 - first_rel[i][2];
            const float dev = sqrtf(dx * dx + dy * dy + dz * dz);
            if (dev > max_dev[i])
                max_dev[i] = dev;
            if (settle < 0 && dev > TWIN_DEV_HIGH)
                settle = TWIN_SETTLE_BRACKETS;
        }
    }
    // Boxed radar/menu passes use their own camera and keep the game's
    // matrices.
    if (boxed)
        return false;
    // Off-hand composite bracket: the whole bracket goes to the left grip,
    // rooted at its seat; no left pose = game animation.
    if (bracket_is_left) {
        if (!have_left_grip) {
            trail_map_hand = -1;
            return false;
        }
        D3DMATRIX rel = vrmod::Multiply(in, root_inv);
        if (vrmod::config.weapon_scale != 1.0f)
            rel = ScaleRel(rel, vrmod::config.weapon_scale);
        const D3DMATRIX& grip = left_on_fist ? grip_world_left_fist : grip_world_left;
        out = vrmod::Multiply(rel, grip);
        NoteTrailMap(root_inv, grip, 0);
        subst_sets_left++;
        return true;
    }
    // Off-hand tail: to the left grip, rooted at its own first part.
    if (split_index > 0 && i >= split_index) {
        if (i == split_index) {
            // Funnel-path twin: this part rides the left hand bone.
            vrmod::hand_bone_world_left = in;
            vrmod::have_hand_bone_left = true;
        }
        if (!have_left_grip) {
            trail_map_hand = -1;
            return false;
        }
        if (i == split_index)
            left_root_inv = vrmod::RigidInverse(in);
        D3DMATRIX rel = vrmod::Multiply(in, left_root_inv);
        if (vrmod::config.weapon_scale != 1.0f)
            rel = ScaleRel(rel, vrmod::config.weapon_scale);
        out = vrmod::Multiply(rel, grip_world_left);
        NoteTrailMap(left_root_inv, grip_world_left, 0);
        subst_sets_left++;
        return true;
    }
    if (!have_grip)
        return false;
    D3DMATRIX rel = vrmod::Multiply(in, root_inv);
    if (vrmod::config.weapon_scale != 1.0f)
        rel = ScaleRel(rel, vrmod::config.weapon_scale);
    const D3DMATRIX& grip = seat_on_fist ? grip_world_fist : grip_world;
    out = vrmod::Multiply(rel, grip);
    NoteTrailMap(root_inv, grip, 1);
    subst_sets++;
    return true;
}

// Once per BeginScene pass, after gamecam::Apply (pose + anchor fresh).
inline void OnFrame() {
    bracket_open = false;
    part_index = 0;
    bracket_fired_last_pass = bracket_fired;
    bracket_drew_last_pass = bracket_drew;
    bracket_drew = false;
    subst_sets_last_pass = subst_sets;
    subst_sets_left_last_pass = subst_sets_left;
    trails_suppressed_last_pass = trails_suppressed;
    diag::trail_kept_last_pass = trail_kept;
    diag::trail_dropped_last_pass = trail_dropped;
    diag::trail_kept_total += (unsigned)trail_kept;
    diag::trail_dropped_total += (unsigned)trail_dropped;
    bracket_fired = false;
    subst_sets = 0;
    subst_sets_left = 0;
    trails_suppressed = 0;
    trail_kept = 0;
    trail_dropped = 0;
    trail_map_hand = -1;
    RestoreTrailMask();  // never left set across passes


    // The weapon pointer (null bare-handed), re-read every pass, and its
    // classification.
    current_weapon = nullptr;
    current_category = 0;
    current_kind = WEAPON_KIND_NONE;
    current_is_gun = false;
    current_twin_funnel = false;
    current_twin_comp = false;
    trail_reshapes = false;
    current_projectile = 0;
    current_fire_override = 0;
    const uintptr_t entity = gamecam::ResolveEntity();
    current_owner = entity;
    if (entity != 0 && diag::Accessible(entity + PLAYER_WEAPON_SLOT, 4, false))
        current_weapon = *reinterpret_cast<void* const*>(entity + PLAYER_WEAPON_SLOT);
    if (current_weapon != nullptr) {
        const uintptr_t w = reinterpret_cast<uintptr_t>(current_weapon);
        if (diag::Accessible(w + WEAPON_CATEGORY_OFFSET, 1, false))
            current_category = *reinterpret_cast<const uint8_t*>(w + WEAPON_CATEGORY_OFFSET);
        if (diag::Accessible(w + WEAPON_PMT_OFFSET, 4, false)) {
            const uintptr_t pmt =
                *reinterpret_cast<const uintptr_t*>(w + WEAPON_PMT_OFFSET);
            if (pmt != 0 && diag::Accessible(pmt + PMT_PROJECTILE_OFFSET, 1, false))
                current_projectile =
                    *reinterpret_cast<const uint8_t*>(pmt + PMT_PROJECTILE_OFFSET);
        }
        uintptr_t attacking_fn = WEAPON_VT_NOOP, idle_fn = WEAPON_VT_NOOP;
        if (diag::Accessible(w, 4, false)) {
            const uintptr_t vt = *reinterpret_cast<const uintptr_t*>(w);
            if (vt != 0 && diag::Accessible(vt + WEAPON_FIRE_OVERRIDE_OFFSET, 4, false))
                current_fire_override =
                    *reinterpret_cast<const uintptr_t*>(vt + WEAPON_FIRE_OVERRIDE_OFFSET);
            if (vt != 0 && diag::Accessible(vt + WEAPON_VT_ATTACKING, 8, false)) {
                attacking_fn = *reinterpret_cast<const uintptr_t*>(vt + WEAPON_VT_ATTACKING);
                idle_fn = *reinterpret_cast<const uintptr_t*>(vt + WEAPON_VT_IDLE);
            }
        }
        const uint32_t flags = diag::Accessible(w + WEAPON_FLAGS_OFFSET, 4, false)
                                   ? *reinterpret_cast<const uint32_t*>(w + WEAPON_FLAGS_OFFSET) : 0;
        const uint8_t variant = diag::Accessible(w + WEAPON_VARIANT_OFFSET, 1, false)
                                    ? *reinterpret_cast<const uint8_t*>(w + WEAPON_VARIANT_OFFSET) : 0;
        current_kind = KindOfCategory(current_category);
        current_is_gun = KindIsGun(current_kind);
        // The twin split's gate: the kinds that are two-handers, and any
        // weapon the held draw draws once per hand (the two-pass flag).
        current_twin_funnel = KindSplitsFunnel(current_kind) ||
                              (flags & WEAPON_FLAG_TWO_PASS) != 0;
        current_twin_comp = KindSplitsComposite(current_kind);
        trail_reshapes = (attacking_fn != WEAPON_VT_NOOP || idle_fn != WEAPON_VT_NOOP) &&
                         PairReshapes(attacking_fn, current_category, variant);
        current_variant = variant;
        current_attacking_fn = attacking_fn;
    }
    if (current_weapon != logged_weapon) {
        logged_weapon = current_weapon;
        seat_attach_bone = -1;   // re-read at the new weapon's first bracket
        seat_on_fist = false;
        draws_left_half = false;
        for (TrailSlot& s : trail_slots)
            s = TrailSlot();
        trail_logged = false;
        if (current_weapon != nullptr && trail_reshapes)
            diag::Log("weapontrail: class 0x%02X variant %d reshapes on attack (attacking "
                      "virtual 0x%08X) - its trail shows during attacks only",
                      current_category, current_variant, (unsigned)current_attacking_fn);
        if (current_weapon != nullptr) {
            const bool old_rule = current_projectile != 0 ||
                                  IsKnownFiringOverride(current_fire_override);
            diag::Log("weapongrip: weapon %p class 0x%02X kind 0x%02X -> %s "
                      "(projectile %d fire override 0x%08X: old rule %s; "
                      "twin funnel=%d comp=%d)",
                      current_weapon, current_category, current_kind,
                      current_is_gun ? "GUN" : "melee", current_projectile,
                      (unsigned)current_fire_override,
                      old_rule == current_is_gun ? "agrees" : "DISAGREES",
                      current_twin_funnel ? 1 : 0, current_twin_comp ? 1 : 0);
        } else {
            diag::Log("weapongrip: bare hands");
        }
    }

    // Weapon changed: relearn the twin split.
    if (current_weapon != learn_weapon) {
        learn_weapon = current_weapon;
        ResetLearning();
    }

    // The hand-bone stash stays valid only while brackets keep drawing
    // (setting matrices, not just opening - see bracket_drew). The world
    // draws on alternating passes, so a 3-pass gap is allowed; longer
    // (unequip, menus, warps, towns) invalidates it.
    if (bracket_drew_last_pass)
        passes_since_bracket = 0;
    else if (passes_since_bracket < 100)
        passes_since_bracket++;
    if (current_weapon == nullptr || passes_since_bracket > 3) {
        vrmod::have_hand_bone_right = false;
        vrmod::have_hand_bone_left = false;
    }
    have_bracket_root_raw = false;

    // The grip target, once per pass; no pose or no takeover = no
    // substitution.
    have_grip = false;
    if (vrmod::config.weapon_grip && installed && gamecam::DrivesView()) {
        D3DMATRIX pose;
        if (vrmod::Get()->GetHandPose(1, pose)) {  // 1 = right hand
            D3DMATRIX hand_world;
            if (gamecam::WorldFromTracking(pose, hand_world)) {
                const D3DMATRIX offset = ActiveGripOffset();
                grip_world = vrmod::Multiply(offset, hand_world);
                grip_world_fist =
                    vrmod::Multiply(vrmod::Multiply(offset, FistTrim()), hand_world);
                have_grip = true;
            }
        }
    }
    // Room space for the trails' speed test (the world-from-room transform
    // is rigid).
    have_trail_room = false;
    if (have_grip) {
        D3DMATRIX world_from_room;
        if (gamecam::WorldFromTracking(vrmod::Identity(), world_from_room)) {
            trail_room_from_world = vrmod::RigidInverse(world_from_room);
            have_trail_room = true;
        }
    }
    // The off-hand grip, whenever a weapon is held (composite brackets need
    // it at once). Same tuple as the main hand: the grip frames are
    // mirrored and the tuples mirror-symmetric.
    have_left_grip = false;
    if (current_weapon != nullptr && vrmod::config.twin_split &&
        vrmod::config.weapon_grip && installed && gamecam::DrivesView()) {
        D3DMATRIX pose;
        if (vrmod::Get()->GetHandPose(0, pose)) {  // 0 = left hand
            D3DMATRIX hand_world;
            if (gamecam::WorldFromTracking(pose, hand_world)) {
                const D3DMATRIX offset = ActiveGripOffset();
                grip_world_left = vrmod::Multiply(offset, hand_world);
                grip_world_left_fist =
                    vrmod::Multiply(vrmod::Multiply(offset, FistTrim()), hand_world);
                have_left_grip = true;
            }
        }
    }

    if (vrmod::config.weapon_grip != prev_enabled) {
        prev_enabled = vrmod::config.weapon_grip;
        if (vrmod::config.weapon_grip)
            log_budget = 8;
    }
    if (vrmod::config.weapon_grip && log_budget > 0) {
        log_budget--;
        diag::Log("weapongrip: weapon=%p cat=0x%02X gun=%d grip=%d gripL=%d split=%d drives=%d fired_last=%d sets_last=%d setsL_last=%d trails_hidden=%d trail_kept=%d trail_dropped=%d reshapes=%d",
                  current_weapon, current_category, current_is_gun ? 1 : 0,
                  have_grip ? 1 : 0, have_left_grip ? 1 : 0, split_index,
                  gamecam::DrivesView() ? 1 : 0,
                  bracket_fired_last_pass ? 1 : 0, subst_sets_last_pass,
                  subst_sets_left_last_pass, trails_suppressed_last_pass,
                  diag::trail_kept_last_pass, diag::trail_dropped_last_pass,
                  trail_reshapes ? 1 : 0);
    }
}

// Called from the first BeginScene; installs unconditionally, behaviour is
// gated at call time.
inline void Install() {
    static bool tried = false;
    if (tried)
        return;
    tried = true;

    MH_STATUS status = MH_Initialize();
    if (status != MH_OK && status != MH_ERROR_ALREADY_INITIALIZED) {
        probe::Log("weapongrip: MH_Initialize failed (%d)", (int)status);
        return;
    }
    if (MH_CreateHook(reinterpret_cast<void*>(WEAPON_HELD_DRAW),
                      reinterpret_cast<void*>(&HookDraw),
                      reinterpret_cast<void**>(&original_draw)) != MH_OK ||
        MH_CreateHook(reinterpret_cast<void*>(WEAPON_COMP_DRAW),
                      reinterpret_cast<void*>(&HookCompDraw),
                      reinterpret_cast<void**>(&original_comp_draw)) != MH_OK ||
        MH_CreateHook(reinterpret_cast<void*>(TRAIL_RENDER),
                      reinterpret_cast<void*>(&HookTrailRender),
                      reinterpret_cast<void**>(&original_trail_render)) != MH_OK ||
        MH_CreateHook(reinterpret_cast<void*>(TRAIL_ADD),
                      reinterpret_cast<void*>(&HookTrailAdd),
                      reinterpret_cast<void**>(&original_trail_add)) != MH_OK ||
        MH_CreateHook(reinterpret_cast<void*>(TRAIL_SLOT_SAMPLE),
                      reinterpret_cast<void*>(&HookTrailSample),
                      reinterpret_cast<void**>(&original_trail_sample)) != MH_OK) {
        probe::Log("weapongrip: MH_CreateHook failed");
        return;
    }
    if (MH_EnableHook(reinterpret_cast<void*>(WEAPON_HELD_DRAW)) != MH_OK ||
        MH_EnableHook(reinterpret_cast<void*>(WEAPON_COMP_DRAW)) != MH_OK ||
        MH_EnableHook(reinterpret_cast<void*>(TRAIL_RENDER)) != MH_OK ||
        MH_EnableHook(reinterpret_cast<void*>(TRAIL_ADD)) != MH_OK ||
        MH_EnableHook(reinterpret_cast<void*>(TRAIL_SLOT_SAMPLE)) != MH_OK) {
        probe::Log("weapongrip: MH_EnableHook failed");
        return;
    }
    installed = true;
    probe::Log("weapongrip: held-weapon draw brackets (funnel 0x%08X + composite 0x%08X) + trail hooks installed (render 0x%08X, add 0x%08X, slot sample 0x%08X)",
               (unsigned)WEAPON_HELD_DRAW, (unsigned)WEAPON_COMP_DRAW,
               (unsigned)TRAIL_RENDER, (unsigned)TRAIL_ADD,
               (unsigned)TRAIL_SLOT_SAMPLE);
}

}  // namespace weapongrip
