// The equipped weapon rides the controller grip pose.
//
// Each equipped item is its own render object (weapons: one class per
// category, ~140, created via the factory table at 0x9C2240 on item
// data[1]). The player entity holds them in a pointer array at +0xDF8
// indexed by the object's slot byte (+0x188): weapon = slot 6 =
// entity+0xE10 (mag slot 1, armor/shield slot 2). The shared base draw
// virtual (vtbl+0x08 = 0x5C4068: hide flag byte +0xF1, then 0x5C407C ->
// NJ model draw 0x83046C) is the on-the-floor representation and draws
// nothing for the held weapon. The held weapon draws through +0x60
// (0x5E8020) and +0x68 (0x5E88CC), which both funnel into 0x5E8088
// (thiscall, this = the weapon object). While that runs with this ==
// [entity+0xE10], every WORLD SetTransform belongs to the weapon.
//
// Re-seat: for each bracketed matrix, rel = part_world x inverse(root)
// (root = the bracket's first matrix, or the attach bone), and the
// substituted world = rel x grip_offset x WorldFromTracking(right hand
// pose). With no hand pose this frame nothing is substituted and the
// weapon follows the game's animation. Bracketed draws are exempt from
// head-trim suppression and body culling (ExemptingDraws()).
//
// Two-handed weapons: (1) the composite held-model draw 0x5E84A8 draws
// one half per call for twin swords and mechguns; halves alternate
// main/off, so odd composite brackets go to the left grip. (2) Funnel
// duals (daggers, knuckles) draw both halves in one bracket; the off-hand
// tail is found by its parts drifting against the root (same-hand parts
// hold within +-0.002 units) and goes to the left grip. Both only for
// two-handed kinds ([vr] twin_split).
//
// [vr] weapon_grip, weapon_scale (uniform scale about the grip, re-seated
// draws only).
#pragma once

#include <cmath>
#include <cstdint>

#include "MinHook.h"
#include "psobbvr_gamecam.hpp"
#include "psobbvr_log.hpp"
#include "psobbvr_probe.hpp"
#include "psobbvr_vr.hpp"

namespace weapongrip {

// The weapon's held-model draw: common callee of the draw-phase virtuals
// +0x60 (0x5E8020) and +0x68 (0x5E88CC), the same in every weapon vtable.
constexpr uintptr_t WEAPON_HELD_DRAW = 0x005E8088;
// Player entity + 0xE10 = the equipped weapon's render object (slot 6).
constexpr uintptr_t PLAYER_WEAPON_SLOT = 0xE10;
// Weapon object fields (base ctor 0x5E959C): byte +0xF3 = item category
// (data[1], < 0xED); dword +0x200 = its ItemPMT stats record. PMT byte
// +0x1F = projectile type (logged only; not the gun test).
constexpr uintptr_t WEAPON_CATEGORY_OFFSET = 0xF3;
constexpr uintptr_t WEAPON_PMT_OFFSET = 0x200;
constexpr uintptr_t PMT_PROJECTILE_OFFSET = 0x1F;
// The gun test: ItemPMT maps each item class (data[1]; every rare weapon
// is its own class) to one of 19 base kinds (table at root+0x14), and a
// weapon is a gun iff its kind is 06 handgun, 07 rifle, 08 mechgun, 09
// shot or 11 launcher. (Projectile type is not reliable: Izmaela, Windmill
// and Mercurius Rod have one but are swung.) The kinds also pick the
// two-handers for the twin split. Baked from this client's ItemPMT;
// tools\weaponsurvey.py --emit-cpp regenerates the table.
constexpr uint8_t WEAPON_KIND_KNUCKLE = 0x00;
constexpr uint8_t WEAPON_KIND_DAGGER = 0x03;
constexpr uint8_t WEAPON_KIND_HANDGUN = 0x06;
constexpr uint8_t WEAPON_KIND_RIFLE = 0x07;
constexpr uint8_t WEAPON_KIND_MECHGUN = 0x08;
constexpr uint8_t WEAPON_KIND_SHOT = 0x09;
constexpr uint8_t WEAPON_KIND_TWIN_SWORD = 0x0F;
constexpr uint8_t WEAPON_KIND_LAUNCHER = 0x11;
constexpr uint8_t WEAPON_KIND_NONE = 0xFF;  // unreadable / no weapon
// Generated by tools\weaponsurvey.py --emit-cpp from ItemPMT.prs (the kind
// table at root+0x14): item category (data[1]) -> base weapon kind, 0xED entries.
constexpr uint8_t WEAPON_KIND_TABLE[0xED] = {
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x00,  // 0x00
    0x10, 0x04, 0x07, 0x07, 0x09, 0x09, 0x10, 0x0B, 0x03, 0x03, 0x01, 0x07, 0x07, 0x0B, 0x06, 0x01,  // 0x10
    0x02, 0x02, 0x0B, 0x01, 0x0C, 0x0C, 0x06, 0x01, 0x10, 0x10, 0x01, 0x10, 0x01, 0x01, 0x0E, 0x0E,  // 0x20
    0x0E, 0x02, 0x02, 0x02, 0x02, 0x02, 0x03, 0x03, 0x03, 0x03, 0x04, 0x04, 0x04, 0x04, 0x04, 0x05,  // 0x30
    0x05, 0x05, 0x06, 0x06, 0x06, 0x07, 0x07, 0x08, 0x08, 0x08, 0x07, 0x08, 0x08, 0x09, 0x09, 0x0A,  // 0x40
    0x0A, 0x01, 0x0A, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0C, 0x0C, 0x0C, 0x0C, 0x0E, 0x0C,  // 0x50
    0x0D, 0x0D, 0x03, 0x04, 0x04, 0x07, 0x07, 0x09, 0x0B, 0x0D, 0x06, 0x07, 0x08, 0x09, 0x0C, 0x01,  // 0x60
    0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0E, 0x0D, 0x09, 0x07,  // 0x70
    0x04, 0x10, 0x0A, 0x08, 0x08, 0x0A, 0x10, 0x10, 0x05, 0x0F, 0x10, 0x11, 0x12, 0x11, 0x03, 0x02,  // 0x80
    0x01, 0x11, 0x12, 0x12, 0x0D, 0x0E, 0x12, 0x02, 0x0D, 0x07, 0x0E, 0x0D, 0x05, 0x02, 0x09, 0x0B,  // 0x90
    0x0F, 0x05, 0x0D, 0x06, 0x12, 0x0F, 0x11, 0x12, 0x00, 0x01, 0x05, 0x01, 0x01, 0x08, 0x02, 0x06,  // 0xA0
    0x08, 0x07, 0x01, 0x0E, 0x01, 0x00, 0x10, 0x10, 0x0F, 0x01, 0x04, 0x04, 0x03, 0x04, 0x04, 0x06,  // 0xB0
    0x11, 0x11, 0x0C, 0x0A, 0x0B, 0x0B, 0x10, 0x10, 0x03, 0x0A, 0x01, 0x04, 0x02, 0x07, 0x04, 0x04,  // 0xC0
    0x02, 0x01, 0x11, 0x04, 0x04, 0x12, 0x01, 0x04, 0x12, 0x01, 0x01, 0x02, 0x01, 0x01, 0x05, 0x10,  // 0xD0
    0x02, 0x0B, 0x03, 0x00, 0x04, 0x0E, 0x0D, 0x0F, 0x06, 0x07, 0x08, 0x09, 0x0C,  // 0xE0
};
inline uint8_t KindOfCategory(uint8_t category) {
    return category < sizeof(WEAPON_KIND_TABLE) ? WEAPON_KIND_TABLE[category]
                                                : WEAPON_KIND_NONE;
}
inline bool KindIsGun(uint8_t kind) {
    return kind == WEAPON_KIND_HANDGUN || kind == WEAPON_KIND_RIFLE ||
           kind == WEAPON_KIND_MECHGUN || kind == WEAPON_KIND_SHOT ||
           kind == WEAPON_KIND_LAUNCHER;
}
// Which kinds are two-handers. Single-hand weapons with animated parts
// (slicers, claws, double sabers) drift like an off-hand half, so the
// split is gated by kind. Funnel duals (both halves in one bracket):
// daggers and knuckles. Composite duals (one half per bracket): mechguns
// and twin swords (e.g. Musashi 0x89, G-Assassin's Sabers 0xA0, Jizai
// 0xB8, S-rank SWORDS 0xA5, TypeSS 0xE7).
inline bool KindSplitsFunnel(uint8_t kind) {
    return kind == WEAPON_KIND_DAGGER || kind == WEAPON_KIND_KNUCKLE;
}
inline bool KindSplitsComposite(uint8_t kind) {
    return kind == WEAPON_KIND_MECHGUN || kind == WEAPON_KIND_TWIN_SWORD;
}
// Per-class fire override at vtbl+0xCC (weapon vtables are 0x100 bytes,
// fixed layout; +0xC8 = the base per-bullet fire virtual 0x5E6578, +0xCC
// = the class's override, the no-op stub 0x61CDB0 for plain guns). Melee
// classes can have real overrides too (saber 0x5FBFE0), so this is a
// known list, complete for this client: every entry calls the base fire
// virtual or a fire sibling. Diagnostic only: the weapon-change log
// compares this older rule with the kind test.
constexpr uintptr_t WEAPON_FIRE_OVERRIDE_OFFSET = 0xCC;
constexpr uintptr_t FIRING_OVERRIDES[] = {
    0x005F8338,  // Spread Needle (class 0x12) + S-rank NEEDLE (0x7F)
    0x005F4620,  // mechgun family, class 0x08 (psobbvr_gunfire.hpp)
    0x006018AC,  // Yasminkov 9000M (class 0x6C)
    0x005EC2BC,  // the shared dual-fire base (Guld Milla 0x4B)
    // The shot family and friends, all projectile 0.
    0x005FE004,  // plain shots, class 0x09 (Shot .. Final Impact) + TypeSH/SHOT
                 // (0xEB): 5 barrels, base fire virtual once per hit pair
    0x005F7E08,  // S-rank SHOT (0x78): same 5-barrel shape
    0x005EBCFC,  // Belra Cannon (0x4D): fire sibling 0x5E6A88 + base virtual
    0x005F2C6C,  // Baranz Launcher (0x67): base virtual x4
    0x005F8D44,  // Dark Meteor (0x9E): own beam spawn from 5 muzzle transforms
    0x005FB6CC,  // Rocket Punch (0x47, mechgun kind): base virtual x2
    0x005F7194,  // S-rank PUNCH (0x84, mechgun kind): same shape
};
inline bool IsKnownFiringOverride(uintptr_t ov) {
    for (uintptr_t k : FIRING_OVERRIDES)
        if (k == ov)
            return true;
    return false;
}
// Photon-trail suppression: swing trails follow the game's arm animation,
// so with the weapon re-seated they would streak along the old path. They
// render (via the untextured-strip helper 0x82B284, world-space vertices)
// through two thiscall routines:
//  - 0x5E9B9C: the trail object's render (vtable 0xB10330; the weapon
//    holds its trail objects in slots +0x1B0..+0x1BC; [this+0x28] bit 1
//    is the class's own skip)
//  - 0x5D0774: a fixed 10-segment ribbon from an inline buffer at
//    this+0xC4
// Suppressed only while the local weapon is re-seated.
constexpr uintptr_t TRAIL_RENDER_A = 0x005E9B9C;
constexpr uintptr_t TRAIL_RENDER_B = 0x005D0774;
constexpr uintptr_t WEAPON_TRAIL_SLOT_FIRST = 0x1B0;
constexpr int WEAPON_TRAIL_SLOT_COUNT = 4;
// Composite weapons (twin swords, mechguns) draw through a second entry
// into the held-model draw code, 0x5E84A8 (thiscall on the weapon
// object). The twin-sword draw override (0x5F57AC) calls it once per
// half: model [this+0xFC] (style 0x30), then the second model swapped in
// from [this+0x1AC] (style 0x23) - first = main hand, second = off hand.
constexpr uintptr_t WEAPON_COMP_DRAW = 0x005E84A8;
// Twin split thresholds: a part's translation drift from its first-seen
// position relative to the bracket root, in game units (same-hand parts
// hold within +-0.002; the off-hand half drifts even at idle).
constexpr int TWIN_MAX_PARTS = 32;
constexpr float TWIN_DEV_HIGH = 0.08f;    // any part crossing this arms the latch
constexpr float TWIN_DEV_LOW = 0.015f;    // cluster membership at latch time
constexpr int TWIN_SETTLE_BRACKETS = 16;  // extra brackets after the first cross

using DrawFn = void(__fastcall*)(void* self, void* edx);
inline DrawFn original_draw = nullptr;
inline DrawFn original_comp_draw = nullptr;
inline DrawFn original_trail_a = nullptr;
inline DrawFn original_trail_b = nullptr;
inline bool installed = false;

// Per-pass state (reset in OnFrame).
inline void* current_weapon = nullptr;  // [entity+0xE10], validated per pass
inline uint8_t current_category = 0;    // weapon item data[1] (byte +0xF3)
inline uint8_t current_kind = WEAPON_KIND_NONE;  // WEAPON_KIND_TABLE[category]
inline bool current_is_gun = false;     // KindIsGun(current_kind)
inline bool current_twin_funnel = false;  // the funnel learner may latch a split
inline bool current_twin_comp = false;    // odd composite brackets are the off hand
inline uint8_t current_projectile = 0;  // the PMT projectile byte (diagnostic)
inline uintptr_t current_fire_override = 0;  // vtbl+0xCC of the weapon object
// The swing gates' weapon test: a melee weapon, or bare hands with
// [vr] swing_unarmed (punches run the same attack state machine).
inline bool SwingWeapon() {
    if (current_weapon == nullptr)
        return vrmod::config.swing_unarmed;
    return !current_is_gun;
}
inline void* logged_weapon = reinterpret_cast<void*>(~uintptr_t(0));  // last classification logged
inline bool bracket_open = false;       // inside the weapon object's draw
inline bool bracket_is_left = false;    // this bracket = the off-hand half
inline bool bracket_learns = false;     // funnel bracket: twin-split learning runs
inline int comp_ordinal = 0;            // composite brackets seen this pass
inline bool have_grip = false;          // grip_world resolved this pass
// The character's hand bone (the weapon seat and the hands' frame): the
// entity's bone matrix array at entity+0xE0 (64 bytes per bone);
// bone[hand_bone_index] x the global root matrix [0xA48980] = the hand's
// world matrix. Bone 48 on every model checked; hands.hpp re-confirms.
constexpr uintptr_t ENTITY_BONES_OFFSET = 0xE0;
constexpr uintptr_t GLOBAL_ROOT_MATRIX = 0x00A48980;
inline int hand_bone_index = 48;
inline bool ArrayBoneWorld(int i, D3DMATRIX& out) {
    const uintptr_t entity = gamecam::ResolveEntity();
    if (entity == 0 || !diag::Accessible(entity + ENTITY_BONES_OFFSET, 4, false))
        return false;
    const uintptr_t bones = *reinterpret_cast<const uintptr_t*>(entity + ENTITY_BONES_OFFSET);
    const uintptr_t m = bones + (uintptr_t)i * 64;
    if (bones == 0 || i < 0 || !diag::Accessible(m, 64, false) ||
        !diag::Accessible(GLOBAL_ROOT_MATRIX, 64, false))
        return false;
    out = vrmod::Multiply(*reinterpret_cast<const D3DMATRIX*>(m),
                          *reinterpret_cast<const D3DMATRIX*>(GLOBAL_ROOT_MATRIX));
    return true;
}
// Rigid delta between two world matrices: translation distance and the
// rotation angle of a x inverse(b).
inline void RigidDelta(const D3DMATRIX& a, const D3DMATRIX& b, float& dist, float& deg) {
    const D3DMATRIX d = vrmod::Multiply(a, vrmod::RigidInverse(b));
    dist = sqrtf(d._41 * d._41 + d._42 * d._42 + d._43 * d._43);
    float c = (d._11 + d._22 + d._33 - 1.0f) * 0.5f;
    if (c > 1.0f) c = 1.0f;
    if (c < -1.0f) c = -1.0f;
    deg = acosf(c) * 180.0f / 3.14159265f;
}
// The main-hand bracket's raw first matrix this pass, for the hands'
// bone-index check (it is the hand bone when the first node is inert).
inline D3DMATRIX bracket_root_raw = vrmod::Identity();
inline bool have_bracket_root_raw = false;
inline void* seat_logged_weapon = nullptr;   // one seat line per weapon
// An attach bone further than this from the first matrix is the wrong
// bone for this model: seat on the first matrix instead.
constexpr float SEAT_BONE_MAX_UNITS = 12.0f;
// The weapon's attach bone: signed byte +0x189 on the equipment object
// (getter 0x5D2450, setter 0x5D240C). The held-model draw 0x5E84A8 reads
// it at 0x5E8505 and parents the model to [owner+0xE0] + 64 * index (then,
// if the index matches a byte at +0x210/+0x211, shifts by the vec3 at
// +0x214/+0x220). 0x5E8088 forces bone 48 only on its photon-blade path
// (flag [this+0x1DC] bit 0x400). Claws store the fist bone (the ctor
// 0x5E959C sets 0x31 for the S-rank claws), which flexes against the hand
// bone, so the seat uses this byte; a weapon off the hand bone is held at
// the game's idle relation to it (fist rest lock) plus the fist_* trim,
// which the hand mesh does not ride.
constexpr uintptr_t WEAPON_ATTACH_BONE_OFFSET = 0x189;
inline int seat_attach_bone = -1;     // the attach bone at the last main-hand bracket
inline bool seat_on_fist = false;     // that bone is not the hand bone
inline int ReadAttachBone() {
    const uintptr_t w = reinterpret_cast<uintptr_t>(current_weapon);
    if (w == 0 || !diag::Accessible(w + WEAPON_ATTACH_BONE_OFFSET, 1, false))
        return -1;
    return *reinterpret_cast<const int8_t*>(w + WEAPON_ATTACH_BONE_OFFSET);
}
inline D3DMATRIX grip_world = vrmod::Identity();  // grip_offset x hand-in-world
// The same plus the fist_* trim, for a weapon on the fist bone.
inline D3DMATRIX grip_world_fist = vrmod::Identity();
// Fist rest lock: a claw is pinned
// to the rigid VR hand at the game's idle relation between fist and hand
// bone, instead of following the fist's flex. fist_rest = attach_bone x
// inverse(hand_bone); the seat composes part x inverse(attach_bone) x
// fist_rest x grip. Locks after FIST_LOCK_BRACKETS consecutive brackets
// moving less than FIST_LOCK_DEG / FIST_LOCK_UNITS; the live relation is
// used until then.
constexpr int FIST_LOCK_BRACKETS = 30;
constexpr float FIST_LOCK_DEG = 1.5f;
constexpr float FIST_LOCK_UNITS = 0.1f;
inline D3DMATRIX fist_rest = vrmod::Identity();
inline bool fist_rest_locked = false;
inline int fist_still_count = 0;
inline D3DMATRIX fist_prev_delta = vrmod::Identity();
inline bool have_fist_prev_delta = false;
inline void ResetFistLock() {
    fist_rest_locked = false;
    fist_still_count = 0;
    have_fist_prev_delta = false;
}
inline int part_index = 0;              // matrix # within the current bracket
inline D3DMATRIX root_inv = vrmod::Identity();  // inverse of the bracket's first matrix
// Twin split state, learned per weapon: parts rigid to the bracket root
// are the main hand; a contiguous tail of drifting parts is the off-hand
// half, re-seated onto the left grip rooted at its own first matrix.
inline void* learn_weapon = nullptr;    // weapon the learn state belongs to
inline bool learn_valid = false;        // baseline rel captured (first bracket)
inline int learn_count = -1;            // part count (order-stable, must hold)
inline float first_rel[TWIN_MAX_PARTS][3] = {};  // baseline rel translations
inline float max_dev[TWIN_MAX_PARTS] = {};       // max drift from baseline
inline int settle = -1;                 // brackets left before latching
inline int split_index = -1;            // first off-hand part; -1 = single-hand
inline D3DMATRIX left_root_inv = vrmod::Identity();
inline bool have_left_grip = false;     // grip_world_left resolved this pass
inline D3DMATRIX grip_world_left = vrmod::Identity();
// Diagnostics (a short log window after the grip is switched on).
inline int log_budget = 0;
inline bool prev_enabled = false;
inline bool bracket_fired_last_pass = false;
inline int subst_sets_last_pass = 0;
inline bool bracket_fired = false;
// A bracket set at least one matrix this pass (the weapon drew). In towns
// the bracket opens every pass but sets nothing (holstered).
inline bool bracket_drew = false;
inline bool bracket_drew_last_pass = false;
inline int subst_sets = 0;
inline int subst_sets_left = 0;         // off-hand re-seats this pass
inline int subst_sets_left_last_pass = 0;
inline int trails_suppressed = 0;       // trail renders skipped this pass
inline int trails_suppressed_last_pass = 0;
// Hand-bone stash keep-alive: passes since a held-weapon bracket last
// fired - see the validity block in OnFrame.
inline int passes_since_bracket = 100;

// True while draws belong to the re-seated weapon: the draw paths skip
// head-trim suppression and body culling (a raised weapon can sit inside
// the head sphere).
inline bool ExemptingDraws() {
    return bracket_open && (have_grip || have_left_grip);
}

// grip_offset: rotation + translation in grip-local axes, labelled as the
// wearer feels them. Held thumb-up, the grip frame's -Z points up along
// the fist and the weapon extends along Y: pitch (tip up/down) = about X,
// roll (spin about the blade) = about Y, yaw (left/right) = about Z.
// Applied Rx*Ry*Rz (row-vector), then fwd_cm along -Z, up_cm along +Y,
// side_cm along +X (through the palm); cm scaled by world_scale.
inline D3DMATRIX GripOffsetMatrix(float pitch_deg, float roll_deg,
                                  float yaw_deg, float fwd_cm, float up_cm,
                                  float side_cm = 0.0f) {
    const float d2r = 3.14159265f / 180.0f;
    // Negated so positive pitch tips the blade/barrel up.
    const float p = -pitch_deg * d2r;
    const float ang_y = roll_deg * d2r;  // felt roll = about Y
    const float ang_z = yaw_deg * d2r;   // felt yaw = about Z
    D3DMATRIX rx = vrmod::Identity(), ry = vrmod::Identity(), rz = vrmod::Identity();
    rx._22 = cosf(p); rx._23 = sinf(p); rx._32 = -sinf(p); rx._33 = cosf(p);
    ry._11 = cosf(ang_y); ry._13 = -sinf(ang_y); ry._31 = sinf(ang_y); ry._33 = cosf(ang_y);
    rz._11 = cosf(ang_z); rz._12 = sinf(ang_z); rz._21 = -sinf(ang_z); rz._22 = cosf(ang_z);
    D3DMATRIX m = vrmod::Multiply(vrmod::Multiply(rx, ry), rz);
    const float cm = 0.01f * vrmod::config.world_scale;
    m._41 = side_cm * cm;
    m._42 = up_cm * cm;
    m._43 = -fwd_cm * cm;
    return m;
}

// The active tuple: guns have their own, separate from melee.
inline D3DMATRIX ActiveGripOffset() {
    if (current_is_gun)
        return GripOffsetMatrix(vrmod::config.gun_pitch_deg,
                                vrmod::config.gun_roll_deg,
                                vrmod::config.gun_yaw_deg,
                                vrmod::config.gun_fwd_cm,
                                vrmod::config.gun_up_cm);
    return GripOffsetMatrix(vrmod::config.grip_pitch_deg,
                            vrmod::config.grip_roll_deg,
                            vrmod::config.grip_yaw_deg,
                            vrmod::config.grip_fwd_cm,
                            vrmod::config.grip_up_cm);
}

// A hand's barrel ray (origin, unit forward, world units): the -Y axis
// (muzzle end) of the frame the gun is drawn in, grip tuple x hand world
// pose, so the ray is the visible barrel. pitch_trim_deg tilts it about
// the weapon's side axis, positive = toward world down. Works for either
// hand (the grip frames and tuples are mirror-symmetric). False with no
// pose or before the head pose is written this frame.
inline bool BarrelRay(int hand, float* origin, float* fwd,
                      float pitch_trim_deg) {
    D3DMATRIX pose, hand_world;
    if (!vrmod::Get()->GetHandPose(hand & 1, pose) ||
        !gamecam::WorldFromTracking(pose, hand_world))
        return false;
    const D3DMATRIX m = vrmod::Multiply(ActiveGripOffset(), hand_world);
    float f[3] = {-m._21, -m._22, -m._23};  // row 2 = the weapon's Y axis; muzzle on -Y
    float len = sqrtf(f[0] * f[0] + f[1] * f[1] + f[2] * f[2]);
    if (len < 1e-6f)
        return false;
    f[0] /= len; f[1] /= len; f[2] /= len;
    if (pitch_trim_deg != 0.0f) {
        // Side axis = row 1 (the weapon's X). t = side x fwd, signed so
        // positive trim tilts toward world down (-Y).
        float ax[3] = {m._11, m._12, m._13};
        const float al = sqrtf(ax[0] * ax[0] + ax[1] * ax[1] + ax[2] * ax[2]);
        if (al > 1e-6f) {
            ax[0] /= al; ax[1] /= al; ax[2] /= al;
            float t[3] = {ax[1] * f[2] - ax[2] * f[1],
                          ax[2] * f[0] - ax[0] * f[2],
                          ax[0] * f[1] - ax[1] * f[0]};
            if (t[1] > 0.0f) {
                t[0] = -t[0]; t[1] = -t[1]; t[2] = -t[2];
            }
            const float a = pitch_trim_deg * (3.14159265f / 180.0f);
            const float c = cosf(a), s = sinf(a);
            for (int i = 0; i < 3; i++)
                f[i] = f[i] * c + t[i] * s;
        }
    }
    fwd[0] = f[0]; fwd[1] = f[1]; fwd[2] = f[2];
    origin[0] = m._41; origin[1] = m._42; origin[2] = m._43;
    return true;
}

inline void ResetLearning() {
    learn_valid = false;
    learn_count = -1;
    settle = -1;
    split_index = -1;
    for (int i = 0; i < TWIN_MAX_PARTS; i++)
        max_dev[i] = 0.0f;
}

// Shared by both bracket hooks (funnel + composite entry). Returns whether
// this call owns the bracket (nested calls fold into the outer bracket).
inline bool BracketOpen(void* self, const char* which, bool left,
                        bool learns) {
    if (bracket_open)
        return false;
    bracket_open = true;
    bracket_is_left = left;
    bracket_learns = learns;
    bracket_fired = true;
    part_index = 0;
    return true;
}

inline void BracketClose() {
    bracket_open = false;
    // Twin-split learning, once per completed funnel bracket (composite
    // brackets split per bracket instead).
    if (!bracket_learns || !vrmod::config.twin_split || !current_twin_funnel ||
        split_index >= 0)
        return;
    if (!learn_valid) {
        if (part_index > 0) {
            learn_count = part_index;
            learn_valid = true;
        }
    } else if (part_index > 0 && part_index != learn_count) {
        // Part count changed (equip transition, effects): relearn.
        ResetLearning();
    } else if (settle >= 0 && settle-- == 0) {
        // Latch: walk back from the last part while it kept moving (the
        // off-hand half is a contiguous tail; part 0 never counts).
        int j = learn_count;
        while (j > 1 && max_dev[j - 1] > TWIN_DEV_LOW)
            j--;
        if (j > 1 && j < learn_count) {
            split_index = j;
            diag::Log("weapongrip: twin split latched at part %d of %d "
                      "(dev: %.3f %.3f %.3f %.3f %.3f %.3f)",
                      j, learn_count, max_dev[0], max_dev[1], max_dev[2],
                      max_dev[3], max_dev[4], max_dev[5]);
        } else {
            // No clean rigid head: not a twin (or not settled); start over.
            ResetLearning();
        }
    }
}

inline void __fastcall HookDraw(void* self, void* edx) {
    const bool owns = self != nullptr && self == current_weapon &&
                      BracketOpen(self, "funnel", false, true);
    original_draw(self, edx);
    if (owns)
        BracketClose();
}

// The composite entry (twin swords, mechguns): called once per half;
// odd brackets within a pass are the off-hand half.
inline void __fastcall HookCompDraw(void* self, void* edx) {
    bool owns = false;
    if (self != nullptr && self == current_weapon) {
        const bool left = vrmod::config.twin_split && current_twin_comp &&
                          (comp_ordinal & 1) != 0;
        owns = BracketOpen(self, "comp", left, false);
        if (owns)
            comp_ordinal++;
    }
    original_comp_draw(self, edx);
    if (owns)
        BracketClose();
}

// True when a trail render's `this` is the re-seated local weapon (the
// inline ribbon) or one of its trail-object slots.
inline bool SuppressTrail(void* self) {
    if (!have_grip || self == nullptr || current_weapon == nullptr)
        return false;
    if (self == current_weapon) {
        trails_suppressed++;
        return true;
    }
    const uintptr_t w = reinterpret_cast<uintptr_t>(current_weapon);
    for (int i = 0; i < WEAPON_TRAIL_SLOT_COUNT; i++) {
        const uintptr_t slot = w + WEAPON_TRAIL_SLOT_FIRST + i * 4;
        if (diag::Accessible(slot, 4, false) &&
            self == *reinterpret_cast<void* const*>(slot)) {
            trails_suppressed++;
            return true;
        }
    }
    return false;
}

inline void __fastcall HookTrailA(void* self, void* edx) {
    if (SuppressTrail(self))
        return;
    original_trail_a(self, edx);
}

inline void __fastcall HookTrailB(void* self, void* edx) {
    if (SuppressTrail(self))
        return;
    original_trail_b(self, edx);
}

// weapon_scale: uniform scale about the weapon root (the point pinned to
// the controller), applied to the part's root-space matrix.
inline D3DMATRIX ScaleRel(D3DMATRIX rel, float s) {
    rel._11 *= s; rel._12 *= s; rel._13 *= s;
    rel._21 *= s; rel._22 *= s; rel._23 *= s;
    rel._31 *= s; rel._32 *= s; rel._33 *= s;
    rel._41 *= s; rel._42 *= s; rel._43 *= s;
    return rel;
}

// Every device WORLD SetTransform on world-space passes. Returns true
// with the re-seated matrix in out.
inline bool SubstituteWorld(const D3DMATRIX& in, D3DMATRIX& out, bool boxed) {
    if (!bracket_open)
        return false;
    const int i = part_index++;
    // Equipment part matrices are rigid, so RigidInverse is exact.
    // The seat root: the first matrix is hand bone x the model's first
    // node, which some weapons rotate (the basic Partisans, the parasols,
    // Glide Divine). So the main hand seats on the weapon's attach bone
    // (WEAPON_ATTACH_BONE_OFFSET) when readable and near the first matrix,
    // else on the first matrix.
    if (i == 0) {
        D3DMATRIX root = in;
        if (!bracket_is_left) {
            bracket_root_raw = in;
            have_bracket_root_raw = true;
            const int attach = ReadAttachBone();
            const int seat_index = attach >= 0 ? attach : hand_bone_index;
            seat_attach_bone = seat_index;
            seat_on_fist = seat_index != hand_bone_index;
            D3DMATRIX bone;
            bool seated_on_bone = false;
            if (ArrayBoneWorld(seat_index, bone)) {
                float dist = 0.0f, deg = 0.0f;
                RigidDelta(in, bone, dist, deg);
                seated_on_bone = dist <= SEAT_BONE_MAX_UNITS;
                if (seated_on_bone)
                    root = bone;
                if (seat_logged_weapon != current_weapon) {
                    seat_logged_weapon = current_weapon;
                    diag::Log("seatbone: attach bone %d%s; first matrix sits %.2f units / %.1f deg off it -> %s",
                              seat_index,
                              seat_on_fist ? " (NOT the hand bone - fist rest lock + trim)" : " (the hand bone)",
                              dist, deg,
                              seated_on_bone ? "seating on the bone" : "too far, seating on the first matrix");
                }
            }
            // Hand-bone stash for the VR hands: the hand bone when the
            // weapon sits on another bone, else the seat root.
            D3DMATRIX hand;
            const bool have_hand =
                seat_on_fist && seated_on_bone && ArrayBoneWorld(hand_bone_index, hand);
            if (have_hand)
                vrmod::hand_bone_world_right = hand;
            else
                vrmod::hand_bone_world_right = root;
            vrmod::have_hand_bone_right = true;
            root_inv = vrmod::RigidInverse(root);
            // Fist rest lock (see fist_rest).
            if (have_hand) {
                const D3DMATRIX delta = vrmod::Multiply(root, vrmod::RigidInverse(hand));
                if (!fist_rest_locked) {
                    if (have_fist_prev_delta) {
                        float dd = 0.0f, ddeg = 0.0f;
                        RigidDelta(delta, fist_prev_delta, dd, ddeg);
                        fist_still_count = (dd <= FIST_LOCK_UNITS && ddeg <= FIST_LOCK_DEG)
                                               ? fist_still_count + 1 : 0;
                    }
                    fist_prev_delta = delta;
                    have_fist_prev_delta = true;
                    if (fist_still_count >= FIST_LOCK_BRACKETS) {
                        fist_rest = delta;
                        fist_rest_locked = true;
                        float rd = 0.0f, rdeg = 0.0f;
                        RigidDelta(root, hand, rd, rdeg);
                        diag::Log("seatbone: fist rest pose locked after %d still brackets (attach bone %.2f units / %.1f deg from the hand bone)",
                                  fist_still_count, rd, rdeg);
                    }
                }
                root_inv = vrmod::Multiply(root_inv, fist_rest_locked ? fist_rest : delta);
            }
        } else {
            root_inv = vrmod::RigidInverse(root);
        }
        // Composite off-hand brackets stash the left bone (the funnel
        // split stashes it at split_index below).
        bracket_drew = true;
        if (bracket_is_left) {
            vrmod::hand_bone_world_left = in;
            vrmod::have_hand_bone_left = true;
        }
    }
    // Twin-split learning (funnel brackets): track each part's drift from
    // its first-seen root-relative translation (part order is stable).
    if (bracket_learns && vrmod::config.twin_split && current_twin_funnel &&
        split_index < 0 && i < TWIN_MAX_PARTS && i > 0) {
        const D3DMATRIX rel = vrmod::Multiply(in, root_inv);
        if (!learn_valid) {
            first_rel[i][0] = rel._41;
            first_rel[i][1] = rel._42;
            first_rel[i][2] = rel._43;
        } else if (i < learn_count) {
            const float dx = rel._41 - first_rel[i][0];
            const float dy = rel._42 - first_rel[i][1];
            const float dz = rel._43 - first_rel[i][2];
            const float dev = sqrtf(dx * dx + dy * dy + dz * dz);
            if (dev > max_dev[i])
                max_dev[i] = dev;
            if (settle < 0 && dev > TWIN_DEV_HIGH)
                settle = TWIN_SETTLE_BRACKETS;
        }
    }
    // Boxed radar/menu passes use their own camera and keep the game's
    // matrices.
    if (boxed)
        return false;
    // Off-hand composite bracket: the whole bracket goes to the left grip,
    // rooted at its own first matrix; no left pose = game animation.
    if (bracket_is_left) {
        if (!have_left_grip)
            return false;
        D3DMATRIX rel = vrmod::Multiply(in, root_inv);
        if (vrmod::config.weapon_scale != 1.0f)
            rel = ScaleRel(rel, vrmod::config.weapon_scale);
        out = vrmod::Multiply(rel, grip_world_left);
        subst_sets_left++;
        return true;
    }
    // Off-hand tail: to the left grip, rooted at its own first part.
    if (split_index > 0 && i >= split_index) {
        if (i == split_index) {
            // Funnel-path twin: this part rides the left hand bone.
            vrmod::hand_bone_world_left = in;
            vrmod::have_hand_bone_left = true;
        }
        if (!have_left_grip)
            return false;
        if (i == split_index)
            left_root_inv = vrmod::RigidInverse(in);
        D3DMATRIX rel = vrmod::Multiply(in, left_root_inv);
        if (vrmod::config.weapon_scale != 1.0f)
            rel = ScaleRel(rel, vrmod::config.weapon_scale);
        out = vrmod::Multiply(rel, grip_world_left);
        subst_sets_left++;
        return true;
    }
    if (!have_grip)
        return false;
    D3DMATRIX rel = vrmod::Multiply(in, root_inv);
    if (vrmod::config.weapon_scale != 1.0f)
        rel = ScaleRel(rel, vrmod::config.weapon_scale);
    out = vrmod::Multiply(rel, seat_on_fist ? grip_world_fist : grip_world);
    subst_sets++;
    return true;
}

// Once per BeginScene pass, after gamecam::Apply (pose + anchor fresh).
inline void OnFrame() {
    bracket_open = false;
    part_index = 0;
    comp_ordinal = 0;
    bracket_fired_last_pass = bracket_fired;
    bracket_drew_last_pass = bracket_drew;
    bracket_drew = false;
    subst_sets_last_pass = subst_sets;
    subst_sets_left_last_pass = subst_sets_left;
    trails_suppressed_last_pass = trails_suppressed;
    bracket_fired = false;
    subst_sets = 0;
    subst_sets_left = 0;
    trails_suppressed = 0;


    // The weapon pointer (null bare-handed), re-read every pass, and its
    // classification.
    current_weapon = nullptr;
    current_category = 0;
    current_kind = WEAPON_KIND_NONE;
    current_is_gun = false;
    current_twin_funnel = false;
    current_twin_comp = false;
    current_projectile = 0;
    current_fire_override = 0;
    const uintptr_t entity = gamecam::ResolveEntity();
    if (entity != 0 && diag::Accessible(entity + PLAYER_WEAPON_SLOT, 4, false))
        current_weapon = *reinterpret_cast<void* const*>(entity + PLAYER_WEAPON_SLOT);
    if (current_weapon != nullptr) {
        const uintptr_t w = reinterpret_cast<uintptr_t>(current_weapon);
        if (diag::Accessible(w + WEAPON_CATEGORY_OFFSET, 1, false))
            current_category = *reinterpret_cast<const uint8_t*>(w + WEAPON_CATEGORY_OFFSET);
        if (diag::Accessible(w + WEAPON_PMT_OFFSET, 4, false)) {
            const uintptr_t pmt =
                *reinterpret_cast<const uintptr_t*>(w + WEAPON_PMT_OFFSET);
            if (pmt != 0 && diag::Accessible(pmt + PMT_PROJECTILE_OFFSET, 1, false))
                current_projectile =
                    *reinterpret_cast<const uint8_t*>(pmt + PMT_PROJECTILE_OFFSET);
        }
        if (diag::Accessible(w, 4, false)) {
            const uintptr_t vt = *reinterpret_cast<const uintptr_t*>(w);
            if (vt != 0 && diag::Accessible(vt + WEAPON_FIRE_OVERRIDE_OFFSET, 4, false))
                current_fire_override =
                    *reinterpret_cast<const uintptr_t*>(vt + WEAPON_FIRE_OVERRIDE_OFFSET);
        }
        current_kind = KindOfCategory(current_category);
        current_is_gun = KindIsGun(current_kind);
        // The twin split's kind gate.
        current_twin_funnel = KindSplitsFunnel(current_kind);
        current_twin_comp = KindSplitsComposite(current_kind);
    }
    if (current_weapon != logged_weapon) {
        logged_weapon = current_weapon;
        seat_attach_bone = -1;   // re-read at the new weapon's first bracket
        seat_on_fist = false;
        ResetFistLock();
        if (current_weapon != nullptr) {
            const bool old_rule = current_projectile != 0 ||
                                  IsKnownFiringOverride(current_fire_override);
            diag::Log("weapongrip: weapon %p class 0x%02X kind 0x%02X -> %s "
                      "(projectile %d fire override 0x%08X: old rule %s; "
                      "twin funnel=%d comp=%d)",
                      current_weapon, current_category, current_kind,
                      current_is_gun ? "GUN" : "melee", current_projectile,
                      (unsigned)current_fire_override,
                      old_rule == current_is_gun ? "agrees" : "DISAGREES",
                      current_twin_funnel ? 1 : 0, current_twin_comp ? 1 : 0);
        } else {
            diag::Log("weapongrip: bare hands");
        }
    }

    // Weapon changed: relearn the twin split.
    if (current_weapon != learn_weapon) {
        learn_weapon = current_weapon;
        ResetLearning();
    }

    // The hand-bone stash stays valid only while brackets keep drawing
    // (setting matrices, not just opening - see bracket_drew). The world
    // draws on alternating passes, so a 3-pass gap is allowed; longer
    // (unequip, menus, warps, towns) invalidates it.
    if (bracket_drew_last_pass)
        passes_since_bracket = 0;
    else if (passes_since_bracket < 100)
        passes_since_bracket++;
    if (current_weapon == nullptr || passes_since_bracket > 3) {
        vrmod::have_hand_bone_right = false;
        vrmod::have_hand_bone_left = false;
    }
    have_bracket_root_raw = false;

    // The grip target, once per pass; no pose or no takeover = no
    // substitution.
    have_grip = false;
    if (vrmod::config.weapon_grip && installed && gamecam::DrivesView()) {
        D3DMATRIX pose;
        if (vrmod::Get()->GetHandPose(1, pose)) {  // 1 = right hand
            D3DMATRIX hand_world;
            if (gamecam::WorldFromTracking(pose, hand_world)) {
                const D3DMATRIX offset = ActiveGripOffset();
                grip_world = vrmod::Multiply(offset, hand_world);
                grip_world_fist = vrmod::Multiply(
                    vrmod::Multiply(offset,
                                    GripOffsetMatrix(vrmod::config.fist_pitch_deg,
                                                     vrmod::config.fist_roll_deg,
                                                     vrmod::config.fist_yaw_deg,
                                                     vrmod::config.fist_fwd_cm,
                                                     vrmod::config.fist_up_cm,
                                                     vrmod::config.fist_side_cm)),
                    hand_world);
                have_grip = true;
            }
        }
    }
    // The off-hand grip, whenever a weapon is held (composite brackets need
    // it at once). Same tuple as the main hand: the grip frames are
    // mirrored and the tuples mirror-symmetric.
    have_left_grip = false;
    if (current_weapon != nullptr && vrmod::config.twin_split &&
        vrmod::config.weapon_grip && installed && gamecam::DrivesView()) {
        D3DMATRIX pose;
        if (vrmod::Get()->GetHandPose(0, pose)) {  // 0 = left hand
            D3DMATRIX hand_world;
            if (gamecam::WorldFromTracking(pose, hand_world)) {
                grip_world_left =
                    vrmod::Multiply(ActiveGripOffset(), hand_world);
                have_left_grip = true;
            }
        }
    }

    if (vrmod::config.weapon_grip != prev_enabled) {
        prev_enabled = vrmod::config.weapon_grip;
        if (vrmod::config.weapon_grip)
            log_budget = 8;
    }
    if (vrmod::config.weapon_grip && log_budget > 0) {
        log_budget--;
        diag::Log("weapongrip: weapon=%p cat=0x%02X gun=%d grip=%d gripL=%d split=%d drives=%d fired_last=%d sets_last=%d setsL_last=%d trails_last=%d",
                  current_weapon, current_category, current_is_gun ? 1 : 0,
                  have_grip ? 1 : 0, have_left_grip ? 1 : 0, split_index,
                  gamecam::DrivesView() ? 1 : 0,
                  bracket_fired_last_pass ? 1 : 0, subst_sets_last_pass,
                  subst_sets_left_last_pass, trails_suppressed_last_pass);
    }
}

// Called from the first BeginScene; installs unconditionally, behaviour is
// gated at call time.
inline void Install() {
    static bool tried = false;
    if (tried)
        return;
    tried = true;

    MH_STATUS status = MH_Initialize();
    if (status != MH_OK && status != MH_ERROR_ALREADY_INITIALIZED) {
        probe::Log("weapongrip: MH_Initialize failed (%d)", (int)status);
        return;
    }
    if (MH_CreateHook(reinterpret_cast<void*>(WEAPON_HELD_DRAW),
                      reinterpret_cast<void*>(&HookDraw),
                      reinterpret_cast<void**>(&original_draw)) != MH_OK ||
        MH_CreateHook(reinterpret_cast<void*>(WEAPON_COMP_DRAW),
                      reinterpret_cast<void*>(&HookCompDraw),
                      reinterpret_cast<void**>(&original_comp_draw)) != MH_OK ||
        MH_CreateHook(reinterpret_cast<void*>(TRAIL_RENDER_A),
                      reinterpret_cast<void*>(&HookTrailA),
                      reinterpret_cast<void**>(&original_trail_a)) != MH_OK ||
        MH_CreateHook(reinterpret_cast<void*>(TRAIL_RENDER_B),
                      reinterpret_cast<void*>(&HookTrailB),
                      reinterpret_cast<void**>(&original_trail_b)) != MH_OK) {
        probe::Log("weapongrip: MH_CreateHook failed");
        return;
    }
    if (MH_EnableHook(reinterpret_cast<void*>(WEAPON_HELD_DRAW)) != MH_OK ||
        MH_EnableHook(reinterpret_cast<void*>(WEAPON_COMP_DRAW)) != MH_OK ||
        MH_EnableHook(reinterpret_cast<void*>(TRAIL_RENDER_A)) != MH_OK ||
        MH_EnableHook(reinterpret_cast<void*>(TRAIL_RENDER_B)) != MH_OK) {
        probe::Log("weapongrip: MH_EnableHook failed");
        return;
    }
    installed = true;
    probe::Log("weapongrip: held-weapon draw brackets (funnel 0x%08X + composite 0x%08X) + trail hooks installed (0x%08X / 0x%08X)",
               (unsigned)WEAPON_HELD_DRAW, (unsigned)WEAPON_COMP_DRAW,
               (unsigned)TRAIL_RENDER_A, (unsigned)TRAIL_RENDER_B);
}

}  // namespace weapongrip
